"""SentinelMesh ML layer — features, preprocessing, anomaly models, registry.

No accuracy / F1 / ROC-AUC / precision / recall / latency / throughput number
appears in this package. Those require a real training + evaluation run
(ADR-024).
"""

from __future__ import annotations

from .features import (
    FEATURE_SCHEMA_VERSION,
    FeatureSchema,
    FeatureVector,
    extract_features,
    schema_for,
)
from .graph import (
    GRAPH_FEATURE_SCHEMA_VERSION,
    ConnectedComponentClusterer,
    GnnNodeAnomalyModel,
    GraphEdge,
    GraphModelRegistry,
    GraphModelUnavailable,
    GraphNode,
    GraphSample,
    LabelPropagationClusterer,
    StructuralGraphAnomaly,
    SuspiciousSubgraphHeuristic,
    build_graph_sample,
)
from .memory import FEATURE_VECTOR_DIM, cosine_similarity, technique_feature_vector
from .models import (
    AnomalyModel,
    AnomalyScore,
    ModelError,
    ModelNotTrained,
    ModelUnavailable,
    StatisticalModel,
)
from .preprocessing import PREPROCESSING_VERSION, Preprocessor
from .registry import ModelRef, ModelRegistry
from .scenario import (
    ScenarioError,
    ScenarioIsolationError,
    ScenarioKind,
    ScenarioRun,
    ScenarioSpec,
    SimEvent,
    SimEventKind,
    SyntheticEntity,
    SyntheticEnvironment,
    SyntheticKind,
    build_synthetic_env,
    is_synthetic_id,
    replay_run,
    run_scenario,
    scenario_id_for,
    validate_spec,
)
from .temporal import (
    EventTimeline,
    ProgressionTrack,
    ReplayCursor,
    Session,
    StitchedTrack,
    TemporalEvent,
    TemporalGraphState,
    build_progression,
    replay,
    stitch_sessions,
)
from .twin import (
    AssetKind,
    AttackPath,
    BlastRadiusReport,
    DefensiveControl,
    RelationKind,
    StressReport,
    TwinAsset,
    TwinModel,
    TwinRelation,
    TwinWeakness,
    WeaknessKind,
    attack_paths,
    blast_radius,
    build_twin,
    stress_test,
    twin_from_synthetic_env,
)

__all__ = [
    "FEATURE_SCHEMA_VERSION",
    "FEATURE_VECTOR_DIM",
    "GRAPH_FEATURE_SCHEMA_VERSION",
    "PREPROCESSING_VERSION",
    "AnomalyModel",
    "AnomalyScore",
    "AssetKind",
    "AttackPath",
    "BlastRadiusReport",
    "ConnectedComponentClusterer",
    "DefensiveControl",
    "EventTimeline",
    "FeatureSchema",
    "FeatureVector",
    "GnnNodeAnomalyModel",
    "GraphEdge",
    "GraphModelRegistry",
    "GraphModelUnavailable",
    "GraphNode",
    "GraphSample",
    "LabelPropagationClusterer",
    "ModelError",
    "ModelNotTrained",
    "ModelRef",
    "ModelRegistry",
    "ModelUnavailable",
    "Preprocessor",
    "ProgressionTrack",
    "RelationKind",
    "ReplayCursor",
    "ScenarioError",
    "ScenarioIsolationError",
    "ScenarioKind",
    "ScenarioRun",
    "ScenarioSpec",
    "Session",
    "SimEvent",
    "SimEventKind",
    "StatisticalModel",
    "StitchedTrack",
    "StressReport",
    "StructuralGraphAnomaly",
    "SuspiciousSubgraphHeuristic",
    "SyntheticEntity",
    "SyntheticEnvironment",
    "SyntheticKind",
    "TemporalEvent",
    "TemporalGraphState",
    "TwinAsset",
    "TwinModel",
    "TwinRelation",
    "TwinWeakness",
    "WeaknessKind",
    "attack_paths",
    "blast_radius",
    "build_graph_sample",
    "build_progression",
    "build_synthetic_env",
    "build_twin",
    "cosine_similarity",
    "extract_features",
    "is_synthetic_id",
    "replay",
    "replay_run",
    "run_scenario",
    "scenario_id_for",
    "schema_for",
    "stitch_sessions",
    "stress_test",
    "technique_feature_vector",
    "twin_from_synthetic_env",
    "validate_spec",
]
