{{- range $name, $svc := .Values.services }}
{{- if $svc.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sm-{{ $name }}
  namespace: {{ $.Values.global.namespaces.app }}
  labels:
    {{- include "sentinelmesh.serviceLabels" (dict "name" $name "root" $) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sm-{{ $name }}
  minReplicas: {{ $svc.hpa.minReplicas }}
  maxReplicas: {{ $svc.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.hpa.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
---
{{- end }}
{{- end }}
{{- if and .Values.frontend.enabled .Values.frontend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sm-frontend
  namespace: {{ .Values.global.namespaces.app }}
  labels:
    {{- include "sentinelmesh.serviceLabels" (dict "name" "frontend" "root" $) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sm-frontend
  minReplicas: {{ .Values.frontend.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.hpa.targetCPUUtilizationPercentage }}
{{- end }}
