{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sm-{{ $name }}
  namespace: {{ $.Values.global.namespaces.app }}
  labels:
    {{- include "sentinelmesh.serviceLabels" (dict "name" $name "root" $) | nindent 4 }}
automountServiceAccountToken: false
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sm-frontend
  namespace: {{ .Values.global.namespaces.app }}
  labels:
    {{- include "sentinelmesh.serviceLabels" (dict "name" "frontend" "root" $) | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
