/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ActorType".
 */
export type ActorType = "user" | "sensor" | "service" | "agent" | "system";
/**
 * @maxItems 200
 */
export type CampaignIds = string[];
export type CreatedAt = string;
export type FirstSeen = string;
export type Id = string;
export type LastSeen = string;
export type SubjectId = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatSubjectType".
 */
export type ThreatSubjectType = "identity" | "host" | "ip" | "domain" | "detection";
/**
 * @maxItems 200
 */
export type TechniqueIds = string[];
export type TenantId = string;
export type UpdatedAt = string;
export type Confidence = "low" | "medium" | "high";
/**
 * @maxItems 50
 */
export type EvidenceRefs = string[];
export type Kind = string;
export type Summary = string;
export type Agent = "detection-agent" | "threat-intel-agent" | "response-orchestration-agent";
/**
 * @minItems 1
 * @maxItems 100
 */
export type Evidence = [EvidenceRef, ...EvidenceRef[]];
export type Content = string;
export type Kind1 = string;
export type Provenance = string;
export type Ref = string;
export type Trusted = boolean;
export type SubjectId1 = string;
export type SubjectType = "detection" | "attack_chain" | "incident";
export type Task = string;
export type Agent1 = "detection-agent" | "threat-intel-agent" | "response-orchestration-agent";
export type Detail = string;
/**
 * @maxItems 100
 */
export type Findings = AgentFinding[];
export type GeneratedAt = string;
export type ActionType = string;
export type Decision = "denied" | "approval_required" | "allowed";
export type Rationale = string;
export type Reversible = boolean;
export type Target = string;
/**
 * @maxItems 50
 */
export type ProposedActions = ProposedActionOut[];
export type Status =
  "completed" | "cancelled" | "timeout" | "step_limit" | "tool_limit" | "budget_exhausted" | "failed";
export type StepsUsed = number;
export type TokensSpent = number;
export type ToolCallsUsed = number;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AlertStatus".
 */
export type AlertStatus = "open" | "acknowledged" | "closed";
export type FromLiveProvider = boolean;
export type ModelId = string;
export type PromptSha256 = string;
export type Provider = string;
export type CreatedAt1 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EntityKind".
 */
export type EntityKind = "identity" | "host" | "ip" | "domain" | "process" | "file";
/**
 * Canonical identifier for the entity.
 */
export type Value = string;
export type FeatureSchemaVersion = string;
export type Id1 = string;
export type IsAnomaly = boolean;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AnomalyMethod".
 */
export type AnomalyMethod = "mad_zscore" | "rolling_quantile" | "isolation_forest" | "autoencoder";
export type ModelVersion = string | null;
/**
 * Score mapped to [0,1].
 */
export type NormalizedScore = number;
export type ObservedAt = string;
export type RawEventId = string | null;
/**
 * Raw model / statistic score (method-specific range).
 */
export type Score = number;
export type TenantId1 = string;
/**
 * The threshold in force when this was scored.
 */
export type Threshold = number;
export type UpdatedAt1 = string;
/**
 * Probabilistic estimate that this is a coordinated chain. Never 1.0.
 */
export type Confidence1 = number;
export type CreatedAt2 = string;
export type DetectionCount = number;
export type DistinctStageCount = number;
export type FirstSeen1 = string;
export type Id2 = string;
export type LastSeen1 = string;
/**
 * Machine-readable caveats, e.g. 'out_of_order_observed', 'conflicting_severity'.
 *
 * @maxItems 32
 */
export type Notes = string[];
/**
 * Furthest kill-chain position reached, normalised.
 */
export type Progression = number;
/**
 * Deterministic chain threat score.
 */
export type Score1 = number;
export type ScoreVersion = string;
/**
 * ADR-013: a model timeout / outage degrades the score, never drops it.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ScoringStatus".
 */
export type ScoringStatus = "ok" | "degraded";
export type DetectionCount1 = number;
/**
 * @maxItems 2000
 */
export type DetectionIds = string[];
export type FirstSeen2 = string;
export type LastSeen2 = string;
export type MaxDetectionScore = number;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Severity".
 */
export type Severity = "info" | "low" | "medium" | "high" | "critical";
/**
 * Kill-chain stage, one per enterprise ATT&CK tactic, in kill-chain order.
 *
 * `unknown` is a real, first-class value: a detection whose techniques the
 * platform cannot place goes here rather than being forced onto a stage.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackStage".
 */
export type AttackStage =
  | "reconnaissance"
  | "resource_development"
  | "initial_access"
  | "execution"
  | "persistence"
  | "privilege_escalation"
  | "defense_evasion"
  | "credential_access"
  | "discovery"
  | "lateral_movement"
  | "collection"
  | "command_and_control"
  | "exfiltration"
  | "impact"
  | "unknown";
export type StageOrder = number;
/**
 * @maxItems 64
 */
export type TechniqueIds1 = string[];
/**
 * @maxItems 15
 */
export type Stages = ChainStageModel[];
/**
 * Lifecycle of a chain's *evidence* — not an analyst verdict.
 *
 * A chain is never automatically `confirmed`; confirmation is a human action on
 * the alert/investigation layer (Constitution §17), not something the
 * correlator asserts.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ChainStatus".
 */
export type ChainStatus = "forming" | "active" | "dormant";
export type SubjectId2 = string;
/**
 * @maxItems 128
 */
export type TechniqueIds2 = string[];
export type TenantId2 = string;
/**
 * At least one member detection matched a threat-intel indicator.
 */
export type TiCorroborated = boolean;
export type UpdatedAt2 = string;
export type WindowStart = string;
export type ChainId = string;
export type Confidence2 = number;
export type DetectionCount2 = number;
/**
 * Distinct real kill-chain stages.
 */
export type DistinctStageCount1 = number;
export type FirstSeen3 = string;
export type LastSeen3 = string;
export type Progression1 = number;
export type Score2 = number;
export type ScoreVersion1 = string;
/**
 * Total stage rows (includes 'unknown').
 */
export type StageCount = number;
export type SubjectId3 = string;
/**
 * @maxItems 128
 */
export type TechniqueIds3 = string[];
export type TenantId3 = string;
export type TiCorroborated1 = boolean;
export type UpdatedAt3 = string;
export type ImportedAt = string;
/**
 * e.g. 'mitre/enterprise'.
 */
export type Source = string;
export type StixBundleSha256 = string;
export type SubtechniqueCount = number;
export type TacticCount = number;
export type TechniqueCount = number;
/**
 * e.g. '14.1'.
 */
export type Version = string;
export type Description = string;
export type MatrixVersion = string;
export type Name = string;
/**
 * STIX x_mitre_shortname.
 */
export type Shortname = string;
export type TacticId = string;
export type Deprecated = boolean;
export type Description1 = string;
export type IsSubtechnique = boolean;
export type MatrixVersion1 = string;
export type Name1 = string;
export type ParentTechniqueId = string | null;
/**
 * @maxItems 16
 */
export type TacticIds = string[];
export type TechniqueId = string;
export type Action = string;
export type ActorId = string | null;
export type CorrelationId = string | null;
export type CreatedAt3 = string;
export type Id3 = string;
/**
 * IPv4/IPv6 textual form.
 */
export type Ip = string | null;
export type RequestId = string | null;
export type ResourceId = string | null;
export type ResourceType = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuditResult".
 */
export type AuditResult = "allow" | "deny" | "success" | "failure";
/**
 * Null for platform-level (cross-tenant) events.
 */
export type TenantId4 = string | null;
/**
 * interactive/network/kerberos/ntlm/ssh/…
 */
export type AuthType = string;
export type FailureReason = string | null;
export type LogonId = string | null;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuthOutcome".
 */
export type AuthOutcome = "success" | "failure";
/**
 * user@domain or username as seen.
 */
export type Principal = string;
export type SourceHost = string | null;
export type SourceIp = string | null;
export type TargetHost = string | null;
export type MaxHops = number;
export type MinWeight = number;
export type Seed = number;
/**
 * @minItems 1
 * @maxItems 20
 */
export type Seeds = [string, ...string[]];
export type AmplifyingWeaknesses = string[];
export type CriticalReached = string[];
export type Reached = string[];
export type Score3 = number;
export type Seed1 = number;
export type Seeds1 = string[];
/**
 * @maxItems 500
 */
export type ChainIds = string[];
export type CreatedAt4 = string;
export type FirstSeen4 = string;
export type Id4 = string;
export type LastSeen4 = string;
export type Status1 = "active" | "dormant" | "closed";
/**
 * @maxItems 200
 */
export type TechniqueIds4 = string[];
export type TenantId5 = string;
export type UpdatedAt4 = string;
/**
 * Normalized verb, e.g. 'connected_to'.
 */
export type Action1 = string;
/**
 * @maxItems 64
 */
export type Entities = EntityRef[];
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CanonicalKind".
 */
export type CanonicalKind = "network_flow" | "auth" | "dns" | "process_exec" | "file_access";
export type OccurredAt1 = string;
export type Outcome = string | null;
/**
 * The telemetry.raw event this was derived from (lineage).
 */
export type RawEventId1 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventType".
 */
export type EventType =
  | "telemetry.network_flow"
  | "telemetry.auth_event"
  | "telemetry.dns_query"
  | "telemetry.process_exec"
  | "telemetry.file_access"
  | "event.canonical"
  | "graph.command"
  | "graph.event"
  | "detection.raised"
  | "attack_chain.updated"
  | "ti.indicator_updated"
  | "agent.task"
  | "response.action"
  | "campaign.updated"
  | "report.generated"
  | "user.event";
export type DisplayName = string;
export type Email = string;
/**
 * System or tenant role names to grant on creation (audited).
 *
 * @maxItems 20
 */
export type RoleNames = string[];
export type Items = AttackChainModel[];
export type Limit = number;
export type NextCursor = string | null;
export type CreatedAt5 = string;
export type DedupKey = string;
export type Description2 = string;
/**
 * How a detection was produced.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DetectorKind".
 */
export type DetectorKind = "rule" | "statistical" | "isolation_forest" | "autoencoder" | "composite";
/**
 * @maxItems 64
 */
export type Entities1 = EntityRef[];
/**
 * What a single piece of detection evidence is.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EvidenceKind".
 */
export type EvidenceKind =
  "event" | "feature" | "rule_match" | "anomaly_score" | "threshold" | "graph_path" | "ti_indicator" | "technique";
/**
 * '<service>:<id>'.
 */
export type Provenance1 = string;
/**
 * Id / key of the evidence subject.
 */
export type Ref1 = string;
export type Summary1 = string;
/**
 * @maxItems 128
 */
export type Evidence1 = EvidenceItem[];
export type FirstSeen5 = string;
export type Id5 = string;
export type LastSeen5 = string;
export type RawEventId2 = string | null;
export type RuleId = string | null;
export type Score4 = number;
/**
 * Detection lifecycle (Constitution §17).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DetectionStatus".
 */
export type DetectionStatus = "new" | "triaged" | "confirmed" | "dismissed" | "suppressed";
/**
 * @maxItems 32
 */
export type TechniqueIds5 = string[];
export type TenantId6 = string;
export type Title = string;
export type UpdatedAt5 = string;
export type Items1 = Detection[];
export type Limit1 = number;
export type NextCursor1 = string | null;
export type AcknowledgedAt = string | null;
export type ClosedAt = string | null;
export type CreatedAt6 = string;
export type DetectionId = string;
export type Id6 = string;
export type OpenedAt = string;
export type Summary2 = string;
export type TenantId7 = string;
export type Title1 = string;
export type UpdatedAt6 = string;
export type Items2 = SecurityAlert[];
export type Limit2 = number;
export type NextCursor2 = string | null;
export type ComputedAt = string;
export type CreatedAt7 = string;
export type Id7 = string;
export type Score5 = number;
export type SubjectId4 = string;
export type TenantId8 = string;
export type UpdatedAt7 = string;
export type WeightsVersion = string;
export type Items3 = ThreatScore[];
export type Limit3 = number;
export type NextCursor3 = string | null;
export type CreatedAt8 = string;
export type Id8 = string;
export type Kind2 = "honeypot_host" | "honeytoken" | "decoy_credential";
export type Name2 = string;
export type NetworkBoundary = "isolated" | "dmz-isolated";
export type Status2 = "active" | "torn_down";
export type Tags = string[];
export type TenantId9 = string;
export type TornDownAt = string | null;
export type TtlSeconds = number;
export type CapturedAt = string;
export type DecoyId = string;
export type Id9 = string;
export type Source1 = string;
export type TechniqueHint = string | null;
export type TenantId10 = string;
/**
 * No secrets, no internals.
 */
export type Detail3 = string | null;
export type Healthy = boolean;
export type LatencyMs = number | null;
export type Name3 = string;
export type DedupKey1 = string;
/**
 * When detection-engine raised it. UTC.
 */
export type DetectedAt = string;
export type DetectionId1 = string;
/**
 * @maxItems 64
 */
export type Entities2 = EntityRef[];
export type EvidenceCount = number;
/**
 * Event time of the telemetry that triggered this. UTC.
 */
export type OccurredAt2 = string;
/**
 * Lineage to the canonical event.
 */
export type RawEventId3 = string | null;
export type RuleId1 = string | null;
/**
 * Composite threat score in [0,1].
 */
export type Score6 = number;
/**
 * Primary subject value.
 */
export type SubjectId5 = string | null;
/**
 * @maxItems 32
 */
export type TechniqueIds6 = string[];
export type TenantId11 = string;
export type Title2 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Direction".
 */
export type Direction = "inbound" | "outbound" | "lateral" | "unknown";
/**
 * @maxItems 64
 */
export type Answers = string[];
export type ClientHost = string | null;
export type ClientIp = string;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt3 = string;
export type QueryName = string;
/**
 * A, AAAA, CNAME, TXT, PTR, MX, …
 */
export type QueryType = string;
export type ResolverIp = string | null;
/**
 * NOERROR/NXDOMAIN/SERVFAIL/…
 */
export type ResponseCode = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "IndicatorFreshness".
 */
export type IndicatorFreshness = "fresh" | "aging" | "stale" | "expired";
export type ActorId1 = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiConfidence".
 */
export type TiConfidence = "low" | "medium" | "high";
export type CreatedAt9 = string;
export type ExpiresAt = string | null;
export type FirstSeen6 = string;
export type Id10 = string;
export type LastSeen6 = string;
/**
 * '<source>' or 'fixture:<name>'.
 */
export type Provider1 = string;
/**
 * URL / feed line / ticket id.
 */
export type Reference = string;
export type RetrievedAt = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiSourceKind".
 */
export type TiSourceKind = "feed" | "api" | "manual" | "fixture";
/**
 * Rule-derived, 1 = most malicious.
 */
export type Reputation = number;
export type Source2 = string;
/**
 * @maxItems 32
 */
export type Tags1 = string[];
/**
 * NULL = platform-global.
 */
export type TenantId12 = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "IndicatorType".
 */
export type IndicatorType = "ipv4" | "ipv6" | "domain" | "url" | "sha256" | "sha1" | "md5" | "email";
export type UpdatedAt8 = string;
/**
 * Normalized (normalize_indicator_value).
 */
export type Value1 = string;
export type Matched = boolean;
export type Value2 = string;
export type Type =
  | "identity"
  | "host"
  | "ip"
  | "domain"
  | "process"
  | "file"
  | "detection"
  | "attack_chain"
  | "attack_technique"
  | "threat_actor"
  | "campaign";
export type Value3 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorCode".
 */
export type ErrorCode =
  | "unauthenticated"
  | "invalid_credentials"
  | "permission_denied"
  | "tenant_forbidden"
  | "not_found"
  | "validation_error"
  | "conflict"
  | "rate_limited"
  | "dependency_unavailable"
  | "degraded_result"
  | "payload_too_large"
  | "unsupported_media_type"
  | "internal_error";
export type CorrelationId1 = string;
/**
 * Dotted path, e.g. 'body.email'.
 */
export type Field = string;
/**
 * Stable machine-readable issue slug.
 */
export type Issue = string;
export type Details = ErrorDetail[];
/**
 * Human-readable, safe to display, contains no internals.
 */
export type Message = string;
export type RequestId1 = string;
export type CorrelationId2 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt4 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer = string;
export type SensorId = string | null;
export type Site = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SourceType".
 */
export type SourceType = "sensor" | "deception" | "simulation" | "internal";
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId13 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId = string | null;
export type CorrelationId3 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId1 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion1 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt1 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt5 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey1 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer1 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId14 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId1 = string | null;
export type CorrelationId4 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId2 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion2 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt2 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt6 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey2 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer2 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId15 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId2 = string | null;
export type CorrelationId5 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId3 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion3 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt3 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt7 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey3 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer3 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId16 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId3 = string | null;
export type CorrelationId6 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId4 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion4 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt4 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt8 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey4 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer4 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId17 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId4 = string | null;
export type CorrelationId7 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId5 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion5 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt5 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt9 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey5 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "FileAction".
 */
export type FileAction = "read" | "write" | "create" | "delete" | "rename" | "execute" | "permission_change";
export type HashSha256 = string | null;
export type Host = string;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt10 = string;
export type Path = string;
export type ProcessId = number | null;
export type ProcessName = string | null;
export type User = string | null;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer5 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId18 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId5 = string | null;
export type CorrelationId8 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId6 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion6 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt6 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt11 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey6 = string;
/**
 * Idempotency key; deterministic per source event + command.
 */
export type CommandId = string;
/**
 * Neo4j label, e.g. ':Host'.
 */
export type Label = string;
export type Label1 = string;
/**
 * Event time from the source event. UTC.
 */
export type ObservedAt1 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphOp".
 */
export type GraphOp = "MERGE_NODE" | "MERGE_EDGE" | "SET_PROPS" | "PRUNE";
/**
 * The canonical/detection event this was derived from (lineage).
 */
export type RawEventId4 = string;
/**
 * Becomes a non-null property on every node/edge (data-model invariant).
 */
export type TenantId19 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer6 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId20 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId6 = string | null;
export type CorrelationId9 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId7 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion7 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt7 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt12 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey7 = string;
/**
 * The `graph.commands` command this reports on.
 */
export type CommandId1 = string;
/**
 * Node label or relationship type.
 */
export type Label2 = string;
export type NodesWritten = number;
/**
 * Event time carried from the command. UTC.
 */
export type ObservedAt2 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphMutationOutcome".
 */
export type GraphMutationOutcome = "APPLIED" | "DUPLICATE" | "STALE";
/**
 * Lineage — the source telemetry/detection event.
 */
export type RawEventId5 = string;
export type RelationshipsWritten = number;
export type TenantId21 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer7 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId22 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId7 = string | null;
export type CorrelationId10 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId8 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion8 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt8 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt13 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey8 = string;
/**
 * e.g. http, dns, ssh.
 */
export type AppProtocol = string | null;
export type BytesReceived = number;
export type BytesSent = number;
export type Direction1 = "inbound" | "outbound" | "lateral" | "unknown";
export type DstHost = string | null;
export type DstIp = string;
export type DstPort = number | null;
export type EndedAt = string | null;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt14 = string;
export type PacketsReceived = number;
export type PacketsSent = number;
/**
 * Transport, e.g. tcp/udp/icmp.
 */
export type Protocol = string;
export type SrcHost = string | null;
export type SrcIp = string;
export type SrcPort = number | null;
/**
 * Firewall/IDS verdict if any.
 */
export type Verdict = string | null;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer8 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId23 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId8 = string | null;
export type CorrelationId11 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId9 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion9 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt9 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt15 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey9 = string;
export type CommandLine = string | null;
export type HashSha2561 = string | null;
export type Host1 = string;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt16 = string;
export type ParentProcessId = number | null;
export type ParentProcessName = string | null;
export type ProcessId1 = number | null;
export type ProcessName1 = string;
export type ProcessPath = string | null;
export type Signed = boolean | null;
export type User1 = string | null;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer9 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId24 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId9 = string | null;
export type CorrelationId12 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId10 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion10 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt10 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt17 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey10 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiUpdateAction".
 */
export type TiUpdateAction = "added" | "updated" | "expired";
export type IndicatorId = string;
export type ObservedAt3 = string;
export type Source3 = string;
export type TenantId25 = string | null;
export type Value4 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer10 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId26 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId10 = string | null;
export type CorrelationId13 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId11 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion11 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt11 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt18 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey11 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserEventAction".
 */
export type UserEventAction =
  | "created"
  | "updated"
  | "disabled"
  | "role_granted"
  | "role_revoked"
  | "login_succeeded"
  | "login_failed"
  | "logged_out";
/**
 * Who performed the action; null for self-service/system.
 */
export type ActorId2 = string | null;
/**
 * Set for role_granted / role_revoked.
 */
export type RoleId = string | null;
export type UserId = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer11 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId27 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId11 = string | null;
/**
 * @minItems 1
 * @maxItems 100
 */
export type Evidence2 = [EvidenceRef, ...EvidenceRef[]];
export type SubjectId6 = string;
export type SubjectType1 = "detection" | "attack_chain" | "incident";
export type Task1 = "summarize" | "triage" | "reason" | "remediate";
/**
 * @maxItems 100
 */
export type CitedRefs = string[];
export type Confidence3 = "low" | "medium" | "high";
export type Degraded = boolean;
export type DegradedReason = string;
export type EvidenceFlagged = boolean;
export type GeneratedAt1 = string;
/**
 * @maxItems 20
 */
export type Recommendations = string[];
export type SubjectId7 = string;
export type SubjectType2 = "detection" | "attack_chain" | "incident";
export type Summary3 = string;
export type RoleId1 = string;
export type Dst = string;
export type Src = string;
export type Type1 = string;
export type Depth = number;
/**
 * @maxItems 20000
 */
export type Edges = GraphEdge[];
export type Id11 = string;
/**
 * @maxItems 32
 */
export type Labels = string[];
/**
 * @maxItems 5000
 */
export type Nodes = GraphNode[];
export type RootId = string;
export type Truncated = boolean;
/**
 * @maxItems 64
 */
export type Edges1 = GraphEdge[];
export type Found = boolean;
export type Length = number | null;
/**
 * @maxItems 64
 */
export type Nodes1 = GraphNode[];
export type Ref2 = string | null;
export type Text = string;
/**
 * How a statement in a report is backed. Every `GroundedStatement` and
 * `ReportTimelineEntry` carries one — never left implicit (Constitution
 * §3).
 *
 * - `evidence`: a real detection/chain/telemetry record the platform
 *   itself produced; `ref` points at it.
 * - `inference`: a deterministic derivation from evidence (e.g. a stage
 *   rollup), not a new observation.
 * - `prediction`: `sm_ml.predict` output — a forecast, never fact
 *   (mirrors `Prediction`, Phase 13).
 * - `synthetic`: from `simulation-service` (Phase 12) demo/scenario data —
 *   never real, always labeled as such.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GroundingKind".
 */
export type GroundingKind = "evidence" | "inference" | "prediction" | "synthetic";
export type Service = string;
export type Status3 = "ok";
export type Version1 = string;
export type CypherFingerprint = string;
export type Explanation1 = string;
export type Intent =
  | "find_entity"
  | "list_related"
  | "path_between"
  | "detections_for"
  | "chains_for"
  | "indicator_sightings"
  | "technique_usage";
export type Intent1 =
  | "find_entity"
  | "list_related"
  | "path_between"
  | "detections_for"
  | "chains_for"
  | "indicator_sightings"
  | "technique_usage";
export type MaxDepth = number;
export type MaxRows = number;
/**
 * @maxItems 8
 */
export type RelTypes = string[];
/**
 * @minItems 1
 * @maxItems 2
 */
export type Selectors = [EntitySelector] | [EntitySelector, EntitySelector];
export type End = string | null;
export type Start = string | null;
export type RowCount = number;
/**
 * @maxItems 500
 */
export type Rows = {
  [k: string]: unknown;
}[];
export type Truncated1 = boolean;
export type Email1 = string;
export type Password = string;
export type TenantSlug = string;
/**
 * Deny-by-default: absence of a code means the action is forbidden.
 *
 * Phase 1 seeds the auth/admin subset. Later phases add their own codes; this
 * enum grows additively.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "PermissionCode".
 */
export type PermissionCode =
  | "users:read"
  | "users:create"
  | "users:update"
  | "roles:read"
  | "roles:grant"
  | "sensors:read"
  | "sensors:manage"
  | "audit:read"
  | "ops:read"
  | "detections:read"
  | "hunt:query"
  | "reports:generate"
  | "response:execute"
  | "response:approve"
  | "simulation:run"
  | "deception:manage"
  | "memory:read"
  | "reports:read";
/**
 * Effective permissions for this session, resolved server-side.
 */
export type Permissions = PermissionCode[];
export type SessionExpiresAt = string;
export type CreatedAt10 = string;
export type DisplayName1 = string;
export type Email2 = string;
/**
 * OIDC `sub` for federated users; null for local-only users.
 */
export type ExternalSubject = string | null;
export type Id12 = string;
export type LastLoginAt = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserStatus".
 */
export type UserStatus = "active" | "disabled" | "invited";
export type TenantId28 = string;
export type UpdatedAt9 = string;
export type Ok = boolean;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MappingConfidence".
 */
export type MappingConfidence = "low" | "medium" | "high";
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MappingSource".
 */
export type MappingSource = "rule" | "graph" | "feature" | "llm" | "analyst";
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MappingSubjectType".
 */
export type MappingSubjectType = "detection" | "attack_chain";
export type Permissions1 = PermissionCode[];
/**
 * Role names granted to the user.
 */
export type Roles = string[];
export type CreatedAt11 = string;
export type Id13 = string;
export type Name4 = string;
/**
 * URL-safe stable identifier, unique across the platform (3-40 chars, no leading/trailing hyphen).
 */
export type Slug = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TenantStatus".
 */
export type TenantStatus = "active" | "suspended";
export type UpdatedAt10 = string;
export type ApiVersion = string;
export type Build = string;
export type Environment = "local" | "ci" | "staging" | "production";
export type Service1 = string;
export type Name5 = string;
export type SubjectCount = number;
export type TacticId1 = string | null;
export type TechniqueId1 = string;
/**
 * @maxItems 1000
 */
export type Cells = MitreHeatmapCell[];
export type MatrixVersion2 = string | null;
export type MaxRows1 = number;
export type Query = string;
export type Action2 = string;
export type Description3 = string;
export type Id14 = string;
export type ResourceType1 = string;
export type Supported = boolean;
export type UnsupportedReason = string;
export type Confidence4 = number;
/**
 * @maxItems 20
 */
export type Evidence3 = string[];
export type GeneratedAt2 = string;
export type Kind3 = "attack_progression" | "lateral_movement" | "next_action" | "threat_trajectory";
export type ModelVersion1 = string;
export type Prediction1 = string;
export type SubjectId8 = string;
export type Dependencies = DepStatus[];
export type Ready = boolean;
export type Kind4 = "honeypot_host" | "honeytoken" | "decoy_credential";
export type Name6 = string;
export type NetworkBoundary1 = "isolated" | "dmz-isolated";
/**
 * @maxItems 20
 */
export type Tags2 = string[];
export type TtlSeconds1 = number;
/**
 * e.g. "victim", "source".
 */
export type Role = string;
export type SubjectId9 = string;
/**
 * @maxItems 200
 */
export type AffectedAssets = ReportAsset[];
/**
 * @maxItems 100
 */
export type ChainIds1 = string[];
export type Confidence5 = number | null;
export type CreatedAt12 = string;
/**
 * @maxItems 500
 */
export type DetectionIds1 = string[];
/**
 * @maxItems 500
 */
export type Evidence4 = GroundedStatement[];
/**
 * @maxItems 200
 */
export type Findings1 = GroundedStatement[];
export type GeneratedAt3 = string | null;
export type Id15 = string;
export type Kind5 = "incident" | "executive_summary" | "soc" | "compliance";
/**
 * @maxItems 20
 */
export type MissingSections = string[];
/**
 * @maxItems 20
 */
export type Provenance3 = string[];
/**
 * @maxItems 200
 */
export type Recommendations1 = GroundedStatement[];
export type RequestedBy = string;
export type Status4 = "pending" | "partial" | "complete" | "failed";
export type StorageKey = string | null;
export type SubjectId10 = string;
/**
 * @maxItems 200
 */
export type TechniqueIds7 = string[];
export type TenantId29 = string;
export type ThreatScore1 = number | null;
export type At = string;
export type Kind6 = string;
export type RefId = string;
/**
 * How a statement in a report is backed. Every `GroundedStatement` and
 * `ReportTimelineEntry` carries one — never left implicit (Constitution
 * §3).
 *
 * - `evidence`: a real detection/chain/telemetry record the platform
 *   itself produced; `ref` points at it.
 * - `inference`: a deterministic derivation from evidence (e.g. a stage
 *   rollup), not a new observation.
 * - `prediction`: `sm_ml.predict` output — a forecast, never fact
 *   (mirrors `Prediction`, Phase 13).
 * - `synthetic`: from `simulation-service` (Phase 12) demo/scenario data —
 *   never real, always labeled as such.
 */
export type GroundingKind1 = "evidence" | "inference" | "prediction" | "synthetic";
export type Title3 = string;
/**
 * @maxItems 500
 */
export type Timeline = ReportTimelineEntry[];
export type Title4 = string;
export type UpdatedAt11 = string;
export type GeneratedAt4 = string;
export type Kind7 = "incident" | "executive_summary" | "soc" | "compliance";
export type ReportId = string;
export type Status5 = "pending" | "partial" | "complete" | "failed";
export type SubjectId11 = string;
export type TenantId30 = string;
export type ComputedAt1 = string;
export type Score7 = number;
export type SubjectId12 = string;
export type CreatedAt13 = string;
export type Description4 = string;
export type Id16 = string;
export type IsSystem = boolean;
export type Name7 = string;
export type TenantId31 = string | null;
export type UpdatedAt12 = string;
export type PermissionId = string;
export type RoleId2 = string;
export type Description5 = string;
export type Id17 = string;
export type IsSystem1 = boolean;
export type Name8 = string;
export type FeedPipeline = boolean;
export type Intensity = number;
export type Kind8 = "apt" | "ransomware" | "insider" | "brute_force";
export type Name9 = string;
export type Seed2 = number;
export type TargetHost1 = string;
export type TargetIdentity = string;
export type EventCount = number;
export type Actor = string;
export type AtOffsetS = number;
export type Kind9 = string;
export type ScenarioId = string;
export type Simulated = boolean;
export type Step = number;
export type Target1 = string;
/**
 * @maxItems 2000
 */
export type Events = SimEventOut[];
export type FedEventCount = number;
export type FedToPipeline = boolean;
export type Intensity1 = number;
export type Kind10 = "apt" | "ransomware" | "insider" | "brute_force";
export type ScenarioId1 = string;
export type Seed3 = number;
export type Synthetic = boolean;
export type TargetHost2 = string;
export type TargetIdentity1 = string;
export type CreatedAt14 = string;
export type Id18 = string;
export type LastSeenAt = string | null;
export type Name10 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SensorStatus".
 */
export type SensorStatus = "active" | "disabled" | "pending";
export type TenantId32 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SensorType".
 */
export type SensorType = "network" | "auth" | "dns" | "process" | "file" | "mixed";
export type UpdatedAt13 = string;
export type ExactFallback = boolean;
export type Id19 = string;
export type Kind11 = "threat_memory" | "campaign" | "adversary_fingerprint";
export type LastSeen7 = string;
export type Score8 = number;
/**
 * @maxItems 200
 */
export type TechniqueIds8 = string[];
export type MaxRows2 = number;
export type Query1 = string | null;
export type HistoryId = string | null;
export type Supported1 = boolean;
export type UnsupportedReason1 = string;
export type ActiveChains = number;
export type Detections24H = number;
export type GeneratedAt5 = string;
export type OpenAlerts = number;
/**
 * @maxItems 20
 */
export type TopRiskSubjects = RiskSubject[];
export type CreatedAt15 = string;
/**
 * @maxItems 64
 */
export type Evidence5 = EvidenceItem[];
export type Id20 = string;
export type MatrixVersion3 = string;
export type Rationale1 = string;
export type SubjectId13 = string;
export type TacticId2 = string | null;
export type TechniqueId2 = string;
export type TenantId33 = string;
export type UpdatedAt14 = string;
export type MatrixVersion4 = string;
export type Name11 = string;
export type Rationale2 = string;
export type TacticId3 = string | null;
export type TacticName = string | null;
export type TechniqueId3 = string;
/**
 * Slug, e.g. 'apt29'.
 */
export type ActorId3 = string;
/**
 * @maxItems 32
 */
export type Aliases = string[];
export type CreatedAt16 = string;
export type Description6 = string;
export type FirstSeen7 = string | null;
export type Id21 = string;
export type LastSeen8 = string | null;
export type Name12 = string;
export type Source4 = string;
export type UpdatedAt15 = string;
export type CreatedAt17 = string;
export type FirstSeen8 = string;
export type Id22 = string;
export type LastSeen9 = string;
export type OccurrenceCount = number;
export type PatternKind = "technique_sequence";
export type Source5 = string;
export type SubjectId14 = string;
/**
 * @maxItems 200
 */
export type TechniqueIds9 = string[];
export type TenantId34 = string;
export type UpdatedAt16 = string;
export type ActorId4 = string | null;
export type CreatedAt18 = string;
export type Description7 = string;
export type FirstSeen9 = string | null;
export type Id23 = string;
export type LastSeen10 = string | null;
export type Name13 = string;
export type TenantId35 = string;
export type UpdatedAt17 = string;
export type CreatedAt19 = string;
export type Enabled = boolean;
export type Id24 = string;
export type IndicatorCount = number;
export type LastPollAt = string | null;
export type LastPollStatus = string | null;
export type Name14 = string;
/**
 * Fresh window; freshness derives from it.
 */
export type TtlSeconds2 = number;
export type UpdatedAt18 = string;
export type At1 = string;
export type Kind12 = string;
export type RefId1 = string;
export type Title5 = string;
/**
 * @maxItems 500
 */
export type Entries = TimelineEntry[];
export type SubjectId15 = string;
export type Criticality = number;
export type Id25 = string;
export type Kind13 = string;
export type Name15 = string;
export type Tags3 = string[];
export type Dst1 = string;
export type Kind14 = string;
export type Src1 = string;
export type Weight = number;
/**
 * @maxItems 200
 */
export type Assets = TwinAssetOut[];
/**
 * @maxItems 1000
 */
export type Relations = TwinRelationOut[];
export type Seed4 = number;
export type Synthetic1 = boolean;
export type AssetId = string;
export type Detail5 = string;
export type Kind15 = string;
export type Severity1 = string;
/**
 * @maxItems 200
 */
export type Weaknesses = TwinWeaknessOut[];
export type CreatedAt20 = string;
export type DisplayName2 = string;
export type Email3 = string;
/**
 * OIDC `sub` for federated users; null for local-only users.
 */
export type ExternalSubject1 = string | null;
export type Id26 = string;
export type LastLoginAt1 = string | null;
export type TenantId36 = string;
export type UpdatedAt19 = string;
export type GrantedAt = string;
export type GrantedBy = string;
export type RoleId3 = string;
export type UserId1 = string;

export interface SentinelMeshContracts {
  [k: string]: unknown;
}
/**
 * One evolving fingerprint per subject — the "has this been seen
 * before" record `campaign_ids` links back to.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AdversaryFingerprint".
 */
export interface AdversaryFingerprint {
  campaign_ids?: CampaignIds;
  created_at: CreatedAt;
  first_seen: FirstSeen;
  id: Id;
  last_seen: LastSeen;
  subject_id: SubjectId;
  subject_type: ThreatSubjectType;
  technique_ids?: TechniqueIds;
  tenant_id: TenantId;
  updated_at: UpdatedAt;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AgentFinding".
 */
export interface AgentFinding {
  confidence?: Confidence;
  evidence_refs?: EvidenceRefs;
  kind: Kind;
  summary: Summary;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AgentRunRequest".
 */
export interface AgentRunRequest {
  agent: Agent;
  evidence: Evidence;
  subject_id: SubjectId1;
  subject_type: SubjectType;
  task: Task;
}
/**
 * One piece of platform-gathered evidence. `trusted` is `True` only for
 * strings SentinelMesh itself produced (a rule id, a numeric score, a catalog
 * technique id); everything telemetry- or third-party-derived is `False` and is
 * fenced as data before it reaches the model.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EvidenceRef".
 */
export interface EvidenceRef {
  content: Content;
  kind: Kind1;
  provenance: Provenance;
  ref: Ref;
  trusted?: Trusted;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AgentRunResult".
 */
export interface AgentRunResult {
  agent: Agent1;
  detail?: Detail;
  findings?: Findings;
  generated_at: GeneratedAt;
  proposed_actions?: ProposedActions;
  status: Status;
  steps_used: StepsUsed;
  tokens_spent: TokensSpent;
  tool_calls_used: ToolCallsUsed;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ProposedActionOut".
 */
export interface ProposedActionOut {
  action_type: ActionType;
  decision?: Decision;
  rationale?: Rationale;
  reversible?: Reversible;
  target: Target;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AnalystModelInfo".
 */
export interface AnalystModelInfo {
  from_live_provider?: FromLiveProvider;
  model_id?: ModelId;
  prompt_sha256?: PromptSha256;
  provider?: Provider;
}
/**
 * One scored feature vector. An anomaly is *evidence*, not a conclusion.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Anomaly".
 */
export interface Anomaly {
  created_at: CreatedAt1;
  entity?: EntityRef | null;
  feature_schema_version: FeatureSchemaVersion;
  features?: Features;
  id: Id1;
  is_anomaly: IsAnomaly;
  method: AnomalyMethod;
  model_version?: ModelVersion;
  normalized_score: NormalizedScore;
  observed_at: ObservedAt;
  raw_event_id?: RawEventId;
  score: Score;
  tenant_id: TenantId1;
  threshold: Threshold;
  updated_at: UpdatedAt1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EntityRef".
 */
export interface EntityRef {
  kind: EntityKind;
  value: Value;
}
export interface Features {
  [k: string]: number;
}
/**
 * The full chain as returned by `correlation-engine`'s read API.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackChainModel".
 */
export interface AttackChainModel {
  confidence: Confidence1;
  created_at: CreatedAt2;
  detection_count: DetectionCount;
  distinct_stage_count: DistinctStageCount;
  first_seen: FirstSeen1;
  id: Id2;
  last_seen: LastSeen1;
  notes?: Notes;
  progression: Progression;
  score: Score1;
  score_version: ScoreVersion;
  scoring_status: ScoringStatus;
  stages?: Stages;
  status: ChainStatus;
  subject_id: SubjectId2;
  subject_type: ThreatSubjectType;
  technique_ids?: TechniqueIds2;
  tenant_id: TenantId2;
  ti_corroborated?: TiCorroborated;
  updated_at: UpdatedAt2;
  window_start: WindowStart;
}
/**
 * One kill-chain stage within a chain, with the detections behind it.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ChainStageModel".
 */
export interface ChainStageModel {
  detection_count: DetectionCount1;
  detection_ids?: DetectionIds;
  first_seen: FirstSeen2;
  last_seen: LastSeen2;
  max_detection_score: MaxDetectionScore;
  max_severity: Severity;
  stage: AttackStage;
  stage_order: StageOrder;
  technique_ids?: TechniqueIds1;
}
/**
 * `attack_chains` topic event (`EventType.attack_chain_updated`).
 *
 * Thin projection: enough to render a chain row and to fan a notification out.
 * The per-stage evidence stays in Postgres.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackChainPayload".
 */
export interface AttackChainPayload {
  chain_id: ChainId;
  confidence: Confidence2;
  detection_count: DetectionCount2;
  distinct_stage_count: DistinctStageCount1;
  first_seen: FirstSeen3;
  last_seen: LastSeen3;
  latest_stage: AttackStage;
  progression: Progression1;
  score: Score2;
  score_version: ScoreVersion1;
  scoring_status: ScoringStatus;
  stage_count: StageCount;
  status: ChainStatus;
  subject_id: SubjectId3;
  subject_type: ThreatSubjectType;
  technique_ids?: TechniqueIds3;
  tenant_id: TenantId3;
  ti_corroborated?: TiCorroborated1;
  updated_at: UpdatedAt3;
}
/**
 * What one import run actually produced. Coverage claims read from here.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackMatrixVersion".
 */
export interface AttackMatrixVersion {
  imported_at: ImportedAt;
  source: Source;
  stix_bundle_sha256: StixBundleSha256;
  subtechnique_count: SubtechniqueCount;
  tactic_count: TacticCount;
  technique_count: TechniqueCount;
  version: Version;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackTactic".
 */
export interface AttackTactic {
  description?: Description;
  matrix_version: MatrixVersion;
  name: Name;
  shortname: Shortname;
  tactic_id: TacticId;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackTechnique".
 */
export interface AttackTechnique {
  deprecated?: Deprecated;
  description?: Description1;
  is_subtechnique?: IsSubtechnique;
  matrix_version: MatrixVersion1;
  name: Name1;
  parent_technique_id?: ParentTechniqueId;
  tactic_ids?: TacticIds;
  technique_id: TechniqueId;
}
/**
 * Append-only audit entry (safe DTO).
 *
 * The storage row additionally carries per-tenant hash-chain columns
 * (`prev_hash`, `hash`) which are an integrity mechanism, not part of the
 * contract.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuditRecord".
 */
export interface AuditRecord {
  action: Action;
  actor_id?: ActorId;
  actor_type: ActorType;
  correlation_id?: CorrelationId;
  created_at: CreatedAt3;
  id: Id3;
  ip?: Ip;
  metadata?: Metadata;
  request_id?: RequestId;
  resource_id?: ResourceId;
  resource_type: ResourceType;
  result: AuditResult;
  tenant_id?: TenantId4;
}
export interface Metadata {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuthEventPayload".
 */
export interface AuthEventPayload {
  auth_type: AuthType;
  failure_reason?: FailureReason;
  logon_id?: LogonId;
  occurred_at: OccurredAt;
  outcome: AuthOutcome;
  principal: Principal;
  source_host?: SourceHost;
  source_ip?: SourceIp;
  target_host?: TargetHost;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "BlastRadiusRequest".
 */
export interface BlastRadiusRequest {
  max_hops?: MaxHops;
  min_weight?: MinWeight;
  seed?: Seed;
  seeds: Seeds;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "BlastRadiusResult".
 */
export interface BlastRadiusResult {
  amplifying_weaknesses?: AmplifyingWeaknesses;
  critical_reached?: CriticalReached;
  hop_of?: HopOf;
  reached?: Reached;
  score: Score3;
  seed: Seed1;
  seeds: Seeds1;
}
export interface HopOf {
  [k: string]: number;
}
/**
 * A set of attack chains judged related by shared technique usage —
 * threat memory's cross-incident view.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Campaign".
 */
export interface Campaign {
  chain_ids?: ChainIds;
  created_at: CreatedAt4;
  first_seen: FirstSeen4;
  id: Id4;
  last_seen: LastSeen4;
  status: Status1;
  technique_ids?: TechniqueIds4;
  tenant_id: TenantId5;
  updated_at: UpdatedAt4;
}
/**
 * The normalized view of one telemetry event. Written by
 * `normalization-engine`, consumed by the graph, detection and memory
 * subsystems.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CanonicalEventPayload".
 */
export interface CanonicalEventPayload {
  action: Action1;
  /**
   * Entity that initiated the event.
   */
  actor?: EntityRef | null;
  attributes?: Attributes;
  enrichment?: Enrichment;
  entities?: Entities;
  kind: CanonicalKind;
  occurred_at: OccurredAt1;
  outcome?: Outcome;
  raw_event_id: RawEventId1;
  raw_event_type: EventType;
  /**
   * Entity acted upon.
   */
  target?: EntityRef | null;
}
/**
 * Normalized flat attributes (ports, bytes, query name, …).
 */
export interface Attributes {
  [k: string]: unknown;
}
/**
 * Enrichment results keyed by provider, each carrying its own provenance and freshness. Absent or partial when a provider was unavailable.
 */
export interface Enrichment {
  [k: string]: unknown;
}
/**
 * Invite/create a user inside the caller's tenant.
 *
 * `tenant_id` is intentionally absent: the server uses the authenticated
 * caller's tenant. Accepting a client-supplied tenant here would be a
 * tenant-injection / mass-assignment flaw (Engineering Constitution §5, §6).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CreateUserRequest".
 */
export interface CreateUserRequest {
  display_name: DisplayName;
  email: Email;
  role_names?: RoleNames;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_AttackChain".
 */
export interface CursorPageAttackChainModel {
  items: Items;
  limit: Limit;
  next_cursor?: NextCursor;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_Detection".
 */
export interface CursorPageDetection {
  items: Items1;
  limit: Limit1;
  next_cursor?: NextCursor1;
}
/**
 * A finding. Every claim it makes is backed by an item in `evidence`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Detection".
 */
export interface Detection {
  created_at: CreatedAt5;
  dedup_key: DedupKey;
  description?: Description2;
  detector: DetectorKind;
  entities?: Entities1;
  evidence?: Evidence1;
  first_seen: FirstSeen5;
  id: Id5;
  last_seen: LastSeen5;
  raw_event_id?: RawEventId2;
  rule_id?: RuleId;
  score: Score4;
  scoring_status: ScoringStatus;
  severity: Severity;
  status: DetectionStatus;
  technique_ids?: TechniqueIds5;
  tenant_id: TenantId6;
  title: Title;
  updated_at: UpdatedAt5;
}
/**
 * One grounded fact behind a detection. `provenance` is `<service>:<id>` so a
 * reader can chase every claim back to its source.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EvidenceItem".
 */
export interface EvidenceItem {
  detail?: Detail1;
  kind: EvidenceKind;
  provenance: Provenance1;
  ref: Ref1;
  summary: Summary1;
}
export interface Detail1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_SecurityAlert".
 */
export interface CursorPageSecurityAlert {
  items: Items2;
  limit: Limit2;
  next_cursor?: NextCursor2;
}
/**
 * Raised from a `Detection` that crosses the alerting threshold. The analyst-
 * facing lifecycle object.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SecurityAlert".
 */
export interface SecurityAlert {
  acknowledged_at?: AcknowledgedAt;
  closed_at?: ClosedAt;
  created_at: CreatedAt6;
  detection_id: DetectionId;
  id: Id6;
  opened_at: OpenedAt;
  severity: Severity;
  status: AlertStatus;
  summary?: Summary2;
  tenant_id: TenantId7;
  title: Title1;
  updated_at: UpdatedAt6;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_ThreatScore".
 */
export interface CursorPageThreatScore {
  items: Items3;
  limit: Limit3;
  next_cursor?: NextCursor3;
}
/**
 * A deterministic composite score for one subject. `components` + `weights_version`
 * make it fully reproducible.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatScore".
 */
export interface ThreatScore {
  components: Components;
  computed_at: ComputedAt;
  created_at: CreatedAt7;
  id: Id7;
  score: Score5;
  scoring_status: ScoringStatus;
  subject_id: SubjectId4;
  subject_type: ThreatSubjectType;
  tenant_id: TenantId8;
  updated_at: UpdatedAt7;
  weights_version: WeightsVersion;
}
/**
 * Named contributions before weighting.
 */
export interface Components {
  [k: string]: number;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Decoy".
 */
export interface Decoy {
  created_at: CreatedAt8;
  id: Id8;
  kind: Kind2;
  name: Name2;
  network_boundary: NetworkBoundary;
  status: Status2;
  tags?: Tags;
  tenant_id: TenantId9;
  torn_down_at?: TornDownAt;
  ttl_seconds: TtlSeconds;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DecoyInteraction".
 */
export interface DecoyInteraction {
  captured_at: CapturedAt;
  decoy_id: DecoyId;
  detail?: Detail2;
  id: Id9;
  source: Source1;
  technique_hint?: TechniqueHint;
  tenant_id: TenantId10;
}
export interface Detail2 {
  [k: string]: string;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DepStatus".
 */
export interface DepStatus {
  detail?: Detail3;
  healthy: Healthy;
  latency_ms?: LatencyMs;
  name: Name3;
}
/**
 * `detections` topic event — the thin projection of a Postgres `detection`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DetectionPayload".
 */
export interface DetectionPayload {
  dedup_key: DedupKey1;
  detected_at: DetectedAt;
  detection_id: DetectionId1;
  detector: DetectorKind;
  entities?: Entities2;
  evidence_count: EvidenceCount;
  occurred_at: OccurredAt2;
  raw_event_id?: RawEventId3;
  rule_id?: RuleId1;
  score: Score6;
  scoring_status: ScoringStatus;
  severity: Severity;
  subject_id?: SubjectId5;
  /**
   * Primary subject of the finding (for correlation into attack chains).
   */
  subject_type?: ThreatSubjectType | null;
  technique_ids?: TechniqueIds6;
  tenant_id: TenantId11;
  title: Title2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DnsQueryPayload".
 */
export interface DnsQueryPayload {
  answers?: Answers;
  client_host?: ClientHost;
  client_ip: ClientIp;
  occurred_at: OccurredAt3;
  query_name: QueryName;
  query_type: QueryType;
  resolver_ip?: ResolverIp;
  response_code?: ResponseCode;
}
/**
 * One result of the enrichment API — was `{type, value}` a known indicator?
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EnrichmentMatch".
 */
export interface EnrichmentMatch {
  freshness?: IndicatorFreshness | null;
  indicator?: ThreatIndicator | null;
  matched: Matched;
  type: IndicatorType;
  value: Value2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatIndicator".
 */
export interface ThreatIndicator {
  actor_id?: ActorId1;
  confidence: TiConfidence;
  created_at: CreatedAt9;
  expires_at?: ExpiresAt;
  first_seen: FirstSeen6;
  freshness: IndicatorFreshness;
  id: Id10;
  last_seen: LastSeen6;
  provenance: Provenance2;
  reputation: Reputation;
  source: Source2;
  tags?: Tags1;
  tenant_id?: TenantId12;
  type: IndicatorType;
  updated_at: UpdatedAt8;
  value: Value1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Provenance".
 */
export interface Provenance2 {
  provider: Provider1;
  reference?: Reference;
  retrieved_at: RetrievedAt;
  source_kind: TiSourceKind;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EntitySelector".
 */
export interface EntitySelector {
  type: Type;
  value: Value3;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  code: ErrorCode;
  correlation_id: CorrelationId1;
  details?: Details;
  message: Message;
  request_id: RequestId1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorDetail".
 */
export interface ErrorDetail {
  field: Field;
  issue: Issue;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_AttackChain".
 */
export interface EventEnvelopeAttackChainPayload {
  correlation_id: CorrelationId2;
  event_id: EventId;
  event_type: EventType;
  event_version: EventVersion;
  ingested_at: IngestedAt;
  metadata?: Metadata1;
  occurred_at: OccurredAt4;
  partition_key: PartitionKey;
  payload: AttackChainPayload;
  producer: Producer;
  source: EventSource;
  tenant_id: TenantId13;
  trace_id?: TraceId;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventSource".
 */
export interface EventSource {
  sensor_id?: SensorId;
  site?: Site;
  type: SourceType;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_AuthEvent".
 */
export interface EventEnvelopeAuthEventPayload {
  correlation_id: CorrelationId3;
  event_id: EventId1;
  event_type: EventType;
  event_version: EventVersion1;
  ingested_at: IngestedAt1;
  metadata?: Metadata2;
  occurred_at: OccurredAt5;
  partition_key: PartitionKey1;
  payload: AuthEventPayload;
  producer: Producer1;
  source: EventSource;
  tenant_id: TenantId14;
  trace_id?: TraceId1;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata2 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_CanonicalEvent".
 */
export interface EventEnvelopeCanonicalEventPayload {
  correlation_id: CorrelationId4;
  event_id: EventId2;
  event_type: EventType;
  event_version: EventVersion2;
  ingested_at: IngestedAt2;
  metadata?: Metadata3;
  occurred_at: OccurredAt6;
  partition_key: PartitionKey2;
  payload: CanonicalEventPayload;
  producer: Producer2;
  source: EventSource;
  tenant_id: TenantId15;
  trace_id?: TraceId2;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata3 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_Detection".
 */
export interface EventEnvelopeDetectionPayload {
  correlation_id: CorrelationId5;
  event_id: EventId3;
  event_type: EventType;
  event_version: EventVersion3;
  ingested_at: IngestedAt3;
  metadata?: Metadata4;
  occurred_at: OccurredAt7;
  partition_key: PartitionKey3;
  payload: DetectionPayload;
  producer: Producer3;
  source: EventSource;
  tenant_id: TenantId16;
  trace_id?: TraceId3;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata4 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_DnsQuery".
 */
export interface EventEnvelopeDnsQueryPayload {
  correlation_id: CorrelationId6;
  event_id: EventId4;
  event_type: EventType;
  event_version: EventVersion4;
  ingested_at: IngestedAt4;
  metadata?: Metadata5;
  occurred_at: OccurredAt8;
  partition_key: PartitionKey4;
  payload: DnsQueryPayload;
  producer: Producer4;
  source: EventSource;
  tenant_id: TenantId17;
  trace_id?: TraceId4;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata5 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_FileAccess".
 */
export interface EventEnvelopeFileAccessPayload {
  correlation_id: CorrelationId7;
  event_id: EventId5;
  event_type: EventType;
  event_version: EventVersion5;
  ingested_at: IngestedAt5;
  metadata?: Metadata6;
  occurred_at: OccurredAt9;
  partition_key: PartitionKey5;
  payload: FileAccessPayload;
  producer: Producer5;
  source: EventSource;
  tenant_id: TenantId18;
  trace_id?: TraceId5;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata6 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "FileAccessPayload".
 */
export interface FileAccessPayload {
  action: FileAction;
  hash_sha256?: HashSha256;
  host: Host;
  occurred_at: OccurredAt10;
  path: Path;
  process_id?: ProcessId;
  process_name?: ProcessName;
  user?: User;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_GraphCommand".
 */
export interface EventEnvelopeGraphCommandPayload {
  correlation_id: CorrelationId8;
  event_id: EventId6;
  event_type: EventType;
  event_version: EventVersion6;
  ingested_at: IngestedAt6;
  metadata?: Metadata7;
  occurred_at: OccurredAt11;
  partition_key: PartitionKey6;
  payload: GraphCommandPayload;
  producer: Producer6;
  source: EventSource;
  tenant_id: TenantId20;
  trace_id?: TraceId6;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata7 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphCommandPayload".
 */
export interface GraphCommandPayload {
  command_id: CommandId;
  end?: GraphEndpoint | null;
  key?: Key1;
  label: Label1;
  observed_at: ObservedAt1;
  op: GraphOp;
  props?: Props;
  raw_event_id: RawEventId4;
  start?: GraphEndpoint | null;
  tenant_id: TenantId19;
}
/**
 * One end of a `MERGE_EDGE` — a node label plus its key.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphEndpoint".
 */
export interface GraphEndpoint {
  key: Key;
  label: Label;
}
/**
 * The node's key property, e.g. {'host_id': 'web01'}.
 */
export interface Key {
  [k: string]: unknown;
}
/**
 * For a node op: its key property. For MERGE_EDGE: unused (see start/end).
 */
export interface Key1 {
  [k: string]: unknown;
}
export interface Props {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_GraphEvent".
 */
export interface EventEnvelopeGraphEventPayload {
  correlation_id: CorrelationId9;
  event_id: EventId7;
  event_type: EventType;
  event_version: EventVersion7;
  ingested_at: IngestedAt7;
  metadata?: Metadata8;
  occurred_at: OccurredAt12;
  partition_key: PartitionKey7;
  payload: GraphEventPayload;
  producer: Producer7;
  source: EventSource;
  tenant_id: TenantId22;
  trace_id?: TraceId7;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata8 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphEventPayload".
 */
export interface GraphEventPayload {
  command_id: CommandId1;
  label: Label2;
  nodes_written?: NodesWritten;
  observed_at: ObservedAt2;
  op: GraphOp;
  outcome: GraphMutationOutcome;
  raw_event_id: RawEventId5;
  relationships_written?: RelationshipsWritten;
  tenant_id: TenantId21;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_NetworkFlow".
 */
export interface EventEnvelopeNetworkFlowPayload {
  correlation_id: CorrelationId10;
  event_id: EventId8;
  event_type: EventType;
  event_version: EventVersion8;
  ingested_at: IngestedAt8;
  metadata?: Metadata9;
  occurred_at: OccurredAt13;
  partition_key: PartitionKey8;
  payload: NetworkFlowPayload;
  producer: Producer8;
  source: EventSource;
  tenant_id: TenantId23;
  trace_id?: TraceId8;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata9 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "NetworkFlowPayload".
 */
export interface NetworkFlowPayload {
  app_protocol?: AppProtocol;
  bytes_received?: BytesReceived;
  bytes_sent?: BytesSent;
  direction?: Direction1;
  dst_host?: DstHost;
  dst_ip: DstIp;
  dst_port?: DstPort;
  ended_at?: EndedAt;
  occurred_at: OccurredAt14;
  packets_received?: PacketsReceived;
  packets_sent?: PacketsSent;
  protocol: Protocol;
  src_host?: SrcHost;
  src_ip: SrcIp;
  src_port?: SrcPort;
  verdict?: Verdict;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_ProcessExec".
 */
export interface EventEnvelopeProcessExecPayload {
  correlation_id: CorrelationId11;
  event_id: EventId9;
  event_type: EventType;
  event_version: EventVersion9;
  ingested_at: IngestedAt9;
  metadata?: Metadata10;
  occurred_at: OccurredAt15;
  partition_key: PartitionKey9;
  payload: ProcessExecPayload;
  producer: Producer9;
  source: EventSource;
  tenant_id: TenantId24;
  trace_id?: TraceId9;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata10 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ProcessExecPayload".
 */
export interface ProcessExecPayload {
  command_line?: CommandLine;
  hash_sha256?: HashSha2561;
  host: Host1;
  occurred_at: OccurredAt16;
  parent_process_id?: ParentProcessId;
  parent_process_name?: ParentProcessName;
  process_id?: ProcessId1;
  process_name: ProcessName1;
  process_path?: ProcessPath;
  signed?: Signed;
  user?: User1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_TiUpdate".
 */
export interface EventEnvelopeTiUpdatePayload {
  correlation_id: CorrelationId12;
  event_id: EventId10;
  event_type: EventType;
  event_version: EventVersion10;
  ingested_at: IngestedAt10;
  metadata?: Metadata11;
  occurred_at: OccurredAt17;
  partition_key: PartitionKey10;
  payload: TiUpdatePayload;
  producer: Producer10;
  source: EventSource;
  tenant_id: TenantId26;
  trace_id?: TraceId10;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata11 {
  [k: string]: unknown;
}
/**
 * `ti.updates` topic event (`EventType.ti_indicator_updated`).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiUpdatePayload".
 */
export interface TiUpdatePayload {
  action: TiUpdateAction;
  confidence: TiConfidence;
  freshness: IndicatorFreshness;
  indicator_id: IndicatorId;
  observed_at: ObservedAt3;
  source: Source3;
  tenant_id?: TenantId25;
  type: IndicatorType;
  value: Value4;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_UserEvent".
 */
export interface EventEnvelopeUserEventPayload {
  correlation_id: CorrelationId13;
  event_id: EventId11;
  event_type: EventType;
  event_version: EventVersion11;
  ingested_at: IngestedAt11;
  metadata?: Metadata12;
  occurred_at: OccurredAt18;
  partition_key: PartitionKey11;
  payload: UserEventPayload;
  producer: Producer11;
  source: EventSource;
  tenant_id: TenantId27;
  trace_id?: TraceId11;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata12 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserEventPayload".
 */
export interface UserEventPayload {
  action: UserEventAction;
  actor_id?: ActorId2;
  role_id?: RoleId;
  user_id: UserId;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ExplainRequest".
 */
export interface ExplainRequest {
  evidence: Evidence2;
  subject_id: SubjectId6;
  subject_type: SubjectType1;
  task?: Task1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Explanation".
 */
export interface Explanation {
  cited_refs?: CitedRefs;
  confidence?: Confidence3;
  degraded?: Degraded;
  degraded_reason?: DegradedReason;
  evidence_flagged?: EvidenceFlagged;
  generated_at: GeneratedAt1;
  model?: AnalystModelInfo;
  recommendations?: Recommendations;
  subject_id: SubjectId7;
  subject_type: SubjectType2;
  summary: Summary3;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GrantRoleRequest".
 */
export interface GrantRoleRequest {
  role_id: RoleId1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphEdge".
 */
export interface GraphEdge {
  dst: Dst;
  properties?: Properties;
  src: Src;
  type: Type1;
}
export interface Properties {
  [k: string]: unknown;
}
/**
 * A bounded, tenant-scoped neighbourhood around one root node.
 *
 * `truncated` is true when the server row cap was hit — the view is partial and
 * the UI must say so rather than implying the entity has no other neighbours.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphNeighborhood".
 */
export interface GraphNeighborhood {
  depth: Depth;
  edges?: Edges;
  nodes?: Nodes;
  root_id: RootId;
  truncated?: Truncated;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphNode".
 */
export interface GraphNode {
  id: Id11;
  labels?: Labels;
  properties?: Properties1;
}
export interface Properties1 {
  [k: string]: unknown;
}
/**
 * The shortest path between two nodes, or `found=False` when there is none.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphPath".
 */
export interface GraphPath {
  edges?: Edges1;
  found: Found;
  length?: Length;
  nodes?: Nodes1;
}
/**
 * One finding, recommendation, or analyst statement. `tier` says which
 * of the four grounding kinds it is; `ref` traces it back to its source
 * (a detection id, a chain id, a prediction id...) whenever `tier` is not
 * `synthetic`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GroundedStatement".
 */
export interface GroundedStatement {
  ref?: Ref2;
  text: Text;
  tier: GroundingKind;
}
/**
 * `GET /healthz` — liveness. The process is up and can serve.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "HealthResponse".
 */
export interface HealthResponse {
  service: Service;
  status?: Status3;
  version: Version1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "HuntResult".
 */
export interface HuntResult {
  cypher_fingerprint?: CypherFingerprint;
  explanation?: Explanation1;
  intent: Intent;
  plan: QueryPlan;
  row_count: RowCount;
  rows?: Rows;
  truncated?: Truncated1;
}
/**
 * A validated, capability-bounded hunt request. Deterministically compiled
 * to a parameterized Cypher template by `graph-service` — never executed as
 * free text.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "QueryPlan".
 */
export interface QueryPlan {
  intent: Intent1;
  limits?: QueryLimits;
  rel_types?: RelTypes;
  selectors: Selectors;
  time_range?: HuntTimeRange | null;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "QueryLimits".
 */
export interface QueryLimits {
  max_depth?: MaxDepth;
  max_rows?: MaxRows;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "HuntTimeRange".
 */
export interface HuntTimeRange {
  end?: End;
  start?: Start;
}
/**
 * Local fallback login. Federated users authenticate via OIDC instead.
 *
 * `tenant_slug` disambiguates the account; the server still resolves the tenant
 * server-side and never trusts a tenant id from the client.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "LoginRequest".
 */
export interface LoginRequest {
  email: Email1;
  password: Password;
  tenant_slug: TenantSlug;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "LoginResponse".
 */
export interface LoginResponse {
  permissions: Permissions;
  session_expires_at: SessionExpiresAt;
  user: User2;
}
/**
 * Safe user DTO.
 *
 * Security state (`password_hash`, `failed_login_count`, `locked_until`) lives
 * only in the api-gateway database model and is never serialized in a contract.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "User".
 */
export interface User2 {
  created_at: CreatedAt10;
  display_name: DisplayName1;
  email: Email2;
  external_subject?: ExternalSubject;
  id: Id12;
  last_login_at?: LastLoginAt;
  status: UserStatus;
  tenant_id: TenantId28;
  updated_at: UpdatedAt9;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "LogoutResponse".
 */
export interface LogoutResponse {
  ok?: Ok;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MeResponse".
 */
export interface MeResponse {
  permissions: Permissions1;
  roles: Roles;
  tenant: Tenant;
  user: User2;
}
/**
 * An isolated customer organization — the root of all data scoping.
 *
 * `Tenant` itself is not tenant-scoped.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Tenant".
 */
export interface Tenant {
  created_at: CreatedAt11;
  id: Id13;
  name: Name4;
  settings?: Settings;
  slug: Slug;
  status: TenantStatus;
  updated_at: UpdatedAt10;
}
export interface Settings {
  [k: string]: unknown;
}
/**
 * `GET /api/v1/meta` — non-sensitive build/runtime info.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MetaResponse".
 */
export interface MetaResponse {
  api_version: ApiVersion;
  build: Build;
  environment: Environment;
  service: Service1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MitreHeatmap".
 */
export interface MitreHeatmap {
  cells?: Cells;
  matrix_version?: MatrixVersion2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MitreHeatmapCell".
 */
export interface MitreHeatmapCell {
  name?: Name5;
  subject_count: SubjectCount;
  tactic_id?: TacticId1;
  technique_id: TechniqueId1;
}
/**
 * A natural-language hunt. `api-gateway` sends this to `ai-analyst`, which
 * returns a `QueryPlan` or `unsupported`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "NlHuntRequest".
 */
export interface NlHuntRequest {
  max_rows?: MaxRows1;
  query: Query;
}
/**
 * An atomic capability. Seeded and immutable; deny-by-default.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Permission".
 */
export interface Permission {
  action: Action2;
  code: PermissionCode;
  description: Description3;
  id: Id14;
  resource_type: ResourceType1;
}
/**
 * `ai-analyst`'s answer to an `NlHuntRequest`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "PlanResponse".
 */
export interface PlanResponse {
  plan?: QueryPlan | null;
  supported: Supported;
  unsupported_reason?: UnsupportedReason;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Prediction".
 */
export interface Prediction {
  confidence: Confidence4;
  evidence?: Evidence3;
  features?: Features1;
  generated_at: GeneratedAt2;
  kind: Kind3;
  model_version: ModelVersion1;
  prediction: Prediction1;
  subject_id: SubjectId8;
  subject_type: ThreatSubjectType | null;
}
export interface Features1 {
  [k: string]: number | string;
}
/**
 * `GET /readyz` — readiness. `ready` is false if any *required* dependency
 * is unreachable; the service should then be pulled from rotation.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ReadyResponse".
 */
export interface ReadyResponse {
  dependencies?: Dependencies;
  ready: Ready;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RegisterDecoyRequest".
 */
export interface RegisterDecoyRequest {
  kind: Kind4;
  name: Name6;
  network_boundary: NetworkBoundary1;
  tags?: Tags2;
  ttl_seconds?: TtlSeconds1;
}
/**
 * A generated report. The rendered artifact (PDF) lives in object
 * storage at `storage_key`; this row is the durable record of what was
 * generated, from what, and how sure the platform is about each part of
 * it. `status` is `partial` (never faked) whenever a content dependency
 * could not be reached — see `missing_sections`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Report".
 */
export interface Report {
  affected_assets?: AffectedAssets;
  chain_ids?: ChainIds1;
  confidence?: Confidence5;
  created_at: CreatedAt12;
  detection_ids?: DetectionIds1;
  evidence?: Evidence4;
  findings?: Findings1;
  generated_at?: GeneratedAt3;
  id: Id15;
  incident_metadata?: IncidentMetadata;
  kind: Kind5;
  missing_sections?: MissingSections;
  provenance?: Provenance3;
  recommendations?: Recommendations1;
  requested_by: RequestedBy;
  status: Status4;
  storage_key?: StorageKey;
  subject_id: SubjectId10;
  subject_type: ThreatSubjectType;
  technique_ids?: TechniqueIds7;
  tenant_id: TenantId29;
  threat_score?: ThreatScore1;
  timeline?: Timeline;
  title: Title4;
  updated_at: UpdatedAt11;
}
/**
 * One affected asset referenced by a report.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ReportAsset".
 */
export interface ReportAsset {
  role: Role;
  subject_id: SubjectId9;
  subject_type: ThreatSubjectType;
}
export interface IncidentMetadata {
  [k: string]: string;
}
/**
 * Timeline point inside a report. Deliberately a separate type from
 * `TimelineEntry` (`api/soc.py`) even though the shape is close — a
 * report's timeline is a persisted, immutable snapshot at generation
 * time, not a live query result, and additionally carries `tier`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ReportTimelineEntry".
 */
export interface ReportTimelineEntry {
  at: At;
  kind: Kind6;
  ref_id: RefId;
  severity?: Severity | null;
  tier?: GroundingKind1;
  title: Title3;
}
/**
 * `report.generated` topic event (`EventType.report_generated`). Thin
 * projection — enough to fan a notification out; the full report (and its
 * rendered artifact) stay in Postgres / object storage.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ReportGeneratedPayload".
 */
export interface ReportGeneratedPayload {
  generated_at: GeneratedAt4;
  kind: Kind7;
  report_id: ReportId;
  status: Status5;
  subject_id: SubjectId11;
  subject_type: ThreatSubjectType;
  tenant_id: TenantId30;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RiskSubject".
 */
export interface RiskSubject {
  computed_at: ComputedAt1;
  score: Score7;
  scoring_status: ScoringStatus;
  subject_id: SubjectId12;
  subject_type: ThreatSubjectType;
}
/**
 * A named bundle of permissions.
 *
 * `tenant_id is None` marks a system role (same definition for every tenant).
 * A tenant-scoped role has a concrete `tenant_id`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Role".
 */
export interface Role1 {
  created_at: CreatedAt13;
  description: Description4;
  id: Id16;
  is_system: IsSystem;
  name: Name7;
  tenant_id?: TenantId31;
  updated_at: UpdatedAt12;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RolePermission".
 */
export interface RolePermission {
  permission_id: PermissionId;
  role_id: RoleId2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RoleSummary".
 */
export interface RoleSummary {
  description: Description5;
  id: Id17;
  is_system: IsSystem1;
  name: Name8;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RunScenarioRequest".
 */
export interface RunScenarioRequest {
  feed_pipeline?: FeedPipeline;
  intensity?: Intensity;
  kind: Kind8;
  name: Name9;
  seed?: Seed2;
  target_host: TargetHost1;
  target_identity: TargetIdentity;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ScenarioRunResult".
 */
export interface ScenarioRunResult {
  event_count: EventCount;
  events?: Events;
  fed_event_count?: FedEventCount;
  fed_to_pipeline?: FedToPipeline;
  intensity: Intensity1;
  kind: Kind10;
  scenario_id: ScenarioId1;
  seed: Seed3;
  synthetic?: Synthetic;
  target_host: TargetHost2;
  target_identity: TargetIdentity1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SimEventOut".
 */
export interface SimEventOut {
  actor: Actor;
  at_offset_s: AtOffsetS;
  attributes?: Attributes1;
  kind: Kind9;
  scenario_id: ScenarioId;
  simulated?: Simulated;
  step: Step;
  target: Target1;
}
export interface Attributes1 {
  [k: string]: string;
}
/**
 * A machine identity that emits telemetry for exactly one tenant.
 *
 * The sensor's `tenant_id` is authoritative for every event it produces; the
 * ingestion path overwrites any tenant value in an inbound payload with this
 * (Engineering Constitution §6).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Sensor".
 */
export interface Sensor {
  created_at: CreatedAt14;
  id: Id18;
  last_seen_at?: LastSeenAt;
  name: Name10;
  status: SensorStatus;
  tenant_id: TenantId32;
  type: SensorType;
  updated_at: UpdatedAt13;
}
/**
 * One result of a similarity search — the record plus its score. The
 * underlying feature vector is never returned.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SimilarityMatch".
 */
export interface SimilarityMatch {
  exact_fallback?: ExactFallback;
  id: Id19;
  kind: Kind11;
  last_seen: LastSeen7;
  score: Score8;
  technique_ids?: TechniqueIds8;
}
/**
 * The browser-facing hunt. Exactly one of `query` (natural language, planned
 * by `ai-analyst`) or `plan` (a structured plan built by the UI, no LLM).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SocHuntRequest".
 */
export interface SocHuntRequest {
  max_rows?: MaxRows2;
  plan?: QueryPlan | null;
  query?: Query1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SocHuntResponse".
 */
export interface SocHuntResponse {
  history_id?: HistoryId;
  result?: HuntResult | null;
  supported: Supported1;
  unsupported_reason?: UnsupportedReason1;
}
/**
 * The dashboard's top-of-page counters. Every number is a real row count for
 * the caller's tenant — never a fabricated figure.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SocSummary".
 */
export interface SocSummary {
  active_chains: ActiveChains;
  alerts_by_severity?: AlertsBySeverity;
  detections_24h: Detections24H;
  generated_at: GeneratedAt5;
  open_alerts: OpenAlerts;
  top_risk_subjects?: TopRiskSubjects;
}
export interface AlertsBySeverity {
  [k: string]: number;
}
/**
 * A persisted subject→technique mapping (Postgres `technique_mapping`).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TechniqueMapping".
 */
export interface TechniqueMapping {
  confidence: MappingConfidence;
  created_at: CreatedAt15;
  evidence?: Evidence5;
  id: Id20;
  matrix_version: MatrixVersion3;
  rationale: Rationale1;
  source: MappingSource;
  subject_id: SubjectId13;
  subject_type: MappingSubjectType;
  tactic_id?: TacticId2;
  technique_id: TechniqueId2;
  tenant_id: TenantId33;
  updated_at: UpdatedAt14;
}
/**
 * One result of the mapping API — a candidate technique for a behaviour.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TechniqueMatch".
 */
export interface TechniqueMatch {
  confidence: MappingConfidence;
  matrix_version: MatrixVersion4;
  name: Name11;
  rationale: Rationale2;
  source: MappingSource;
  tactic_id?: TacticId3;
  tactic_name?: TacticName;
  technique_id: TechniqueId3;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatActor".
 */
export interface ThreatActor {
  actor_id: ActorId3;
  aliases?: Aliases;
  created_at: CreatedAt16;
  description?: Description6;
  first_seen?: FirstSeen7;
  id: Id21;
  last_seen?: LastSeen8;
  name: Name12;
  source: Source4;
  updated_at: UpdatedAt15;
}
/**
 * A behavioral pattern observed for one subject — upserted as the
 * subject's technique set grows, never duplicated per occurrence.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatMemory".
 */
export interface ThreatMemory {
  created_at: CreatedAt17;
  first_seen: FirstSeen8;
  id: Id22;
  last_seen: LastSeen9;
  occurrence_count: OccurrenceCount;
  pattern_kind: PatternKind;
  source: Source5;
  subject_id: SubjectId14;
  subject_type: ThreatSubjectType;
  technique_ids?: TechniqueIds9;
  tenant_id: TenantId34;
  updated_at: UpdatedAt16;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiCampaign".
 */
export interface TiCampaign {
  actor_id?: ActorId4;
  created_at: CreatedAt18;
  description?: Description7;
  first_seen?: FirstSeen9;
  id: Id23;
  last_seen?: LastSeen10;
  name: Name13;
  tenant_id: TenantId35;
  updated_at: UpdatedAt17;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiSource".
 */
export interface TiSource {
  created_at: CreatedAt19;
  enabled: Enabled;
  id: Id24;
  indicator_count?: IndicatorCount;
  kind: TiSourceKind;
  last_poll_at?: LastPollAt;
  last_poll_status?: LastPollStatus;
  name: Name14;
  ttl_seconds: TtlSeconds2;
  updated_at: UpdatedAt18;
}
/**
 * One point on an entity's timeline — a detection, an alert transition, or a
 * chain-stage advance. `kind` distinguishes them for the UI.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TimelineEntry".
 */
export interface TimelineEntry {
  at: At1;
  detail?: Detail4;
  kind: Kind12;
  ref_id: RefId1;
  severity?: Severity | null;
  title: Title5;
}
export interface Detail4 {
  [k: string]: string;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TimelineResponse".
 */
export interface TimelineResponse {
  entries?: Entries;
  subject_id: SubjectId15;
  subject_type: ThreatSubjectType;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TwinAssetOut".
 */
export interface TwinAssetOut {
  criticality: Criticality;
  id: Id25;
  kind: Kind13;
  name?: Name15;
  tags?: Tags3;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TwinRelationOut".
 */
export interface TwinRelationOut {
  dst: Dst1;
  kind: Kind14;
  src: Src1;
  weight: Weight;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TwinSnapshot".
 */
export interface TwinSnapshot {
  assets?: Assets;
  relations?: Relations;
  seed: Seed4;
  synthetic?: Synthetic1;
  weaknesses?: Weaknesses;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TwinWeaknessOut".
 */
export interface TwinWeaknessOut {
  asset_id: AssetId;
  detail?: Detail5;
  kind: Kind15;
  severity: Severity1;
}
/**
 * Response alias for `User` — kept as an explicit type so the API surface is
 * named independently of the internal entity.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserResponse".
 */
export interface UserResponse {
  created_at: CreatedAt20;
  display_name: DisplayName2;
  email: Email3;
  external_subject?: ExternalSubject1;
  id: Id26;
  last_login_at?: LastLoginAt1;
  status: UserStatus;
  tenant_id: TenantId36;
  updated_at: UpdatedAt19;
}
/**
 * A role assignment. Roles are only ever added via this record — there is no
 * request field anywhere that can grant a role or permission
 * (Engineering Constitution §5, §6: role-escalation prevention).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserRoleGrant".
 */
export interface UserRoleGrant {
  granted_at: GrantedAt;
  granted_by: GrantedBy;
  role_id: RoleId3;
  user_id: UserId1;
}
