/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ActorType".
 */
export type ActorType = "user" | "sensor" | "service" | "agent" | "system";
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AlertStatus".
 */
export type AlertStatus = "open" | "acknowledged" | "closed";
export type CreatedAt = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EntityKind".
 */
export type EntityKind = "identity" | "host" | "ip" | "domain" | "process" | "file";
/**
 * Canonical identifier for the entity.
 */
export type Value = string;
export type FeatureSchemaVersion = string;
export type Id = string;
export type IsAnomaly = boolean;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AnomalyMethod".
 */
export type AnomalyMethod = "mad_zscore" | "rolling_quantile" | "isolation_forest" | "autoencoder";
export type ModelVersion = string | null;
/**
 * Score mapped to [0,1].
 */
export type NormalizedScore = number;
export type ObservedAt = string;
export type RawEventId = string | null;
/**
 * Raw model / statistic score (method-specific range).
 */
export type Score = number;
export type TenantId = string;
/**
 * The threshold in force when this was scored.
 */
export type Threshold = number;
export type UpdatedAt = string;
/**
 * Probabilistic estimate that this is a coordinated chain. Never 1.0.
 */
export type Confidence = number;
export type CreatedAt1 = string;
export type DetectionCount = number;
export type DistinctStageCount = number;
export type FirstSeen = string;
export type Id1 = string;
export type LastSeen = string;
/**
 * Machine-readable caveats, e.g. 'out_of_order_observed', 'conflicting_severity'.
 *
 * @maxItems 32
 */
export type Notes = string[];
/**
 * Furthest kill-chain position reached, normalised.
 */
export type Progression = number;
/**
 * Deterministic chain threat score.
 */
export type Score1 = number;
export type ScoreVersion = string;
/**
 * ADR-013: a model timeout / outage degrades the score, never drops it.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ScoringStatus".
 */
export type ScoringStatus = "ok" | "degraded";
export type DetectionCount1 = number;
/**
 * @maxItems 2000
 */
export type DetectionIds = string[];
export type FirstSeen1 = string;
export type LastSeen1 = string;
export type MaxDetectionScore = number;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Severity".
 */
export type Severity = "info" | "low" | "medium" | "high" | "critical";
/**
 * Kill-chain stage, one per enterprise ATT&CK tactic, in kill-chain order.
 *
 * `unknown` is a real, first-class value: a detection whose techniques the
 * platform cannot place goes here rather than being forced onto a stage.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackStage".
 */
export type AttackStage =
  | "reconnaissance"
  | "resource_development"
  | "initial_access"
  | "execution"
  | "persistence"
  | "privilege_escalation"
  | "defense_evasion"
  | "credential_access"
  | "discovery"
  | "lateral_movement"
  | "collection"
  | "command_and_control"
  | "exfiltration"
  | "impact"
  | "unknown";
export type StageOrder = number;
/**
 * @maxItems 64
 */
export type TechniqueIds = string[];
/**
 * @maxItems 15
 */
export type Stages = ChainStageModel[];
/**
 * Lifecycle of a chain's *evidence* — not an analyst verdict.
 *
 * A chain is never automatically `confirmed`; confirmation is a human action on
 * the alert/investigation layer (Constitution §17), not something the
 * correlator asserts.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ChainStatus".
 */
export type ChainStatus = "forming" | "active" | "dormant";
export type SubjectId = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatSubjectType".
 */
export type ThreatSubjectType = "identity" | "host" | "ip" | "domain" | "detection";
/**
 * @maxItems 128
 */
export type TechniqueIds1 = string[];
export type TenantId1 = string;
/**
 * At least one member detection matched a threat-intel indicator.
 */
export type TiCorroborated = boolean;
export type UpdatedAt1 = string;
export type WindowStart = string;
export type ChainId = string;
export type Confidence1 = number;
export type DetectionCount2 = number;
/**
 * Distinct real kill-chain stages.
 */
export type DistinctStageCount1 = number;
export type FirstSeen2 = string;
export type LastSeen2 = string;
export type Progression1 = number;
export type Score2 = number;
export type ScoreVersion1 = string;
/**
 * Total stage rows (includes 'unknown').
 */
export type StageCount = number;
export type SubjectId1 = string;
/**
 * @maxItems 128
 */
export type TechniqueIds2 = string[];
export type TenantId2 = string;
export type TiCorroborated1 = boolean;
export type UpdatedAt2 = string;
export type ImportedAt = string;
/**
 * e.g. 'mitre/enterprise'.
 */
export type Source = string;
export type StixBundleSha256 = string;
export type SubtechniqueCount = number;
export type TacticCount = number;
export type TechniqueCount = number;
/**
 * e.g. '14.1'.
 */
export type Version = string;
export type Description = string;
export type MatrixVersion = string;
export type Name = string;
/**
 * STIX x_mitre_shortname.
 */
export type Shortname = string;
export type TacticId = string;
export type Deprecated = boolean;
export type Description1 = string;
export type IsSubtechnique = boolean;
export type MatrixVersion1 = string;
export type Name1 = string;
export type ParentTechniqueId = string | null;
/**
 * @maxItems 16
 */
export type TacticIds = string[];
export type TechniqueId = string;
export type Action = string;
export type ActorId = string | null;
export type CorrelationId = string | null;
export type CreatedAt2 = string;
export type Id2 = string;
/**
 * IPv4/IPv6 textual form.
 */
export type Ip = string | null;
export type RequestId = string | null;
export type ResourceId = string | null;
export type ResourceType = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuditResult".
 */
export type AuditResult = "allow" | "deny" | "success" | "failure";
/**
 * Null for platform-level (cross-tenant) events.
 */
export type TenantId3 = string | null;
/**
 * interactive/network/kerberos/ntlm/ssh/…
 */
export type AuthType = string;
export type FailureReason = string | null;
export type LogonId = string | null;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuthOutcome".
 */
export type AuthOutcome = "success" | "failure";
/**
 * user@domain or username as seen.
 */
export type Principal = string;
export type SourceHost = string | null;
export type SourceIp = string | null;
export type TargetHost = string | null;
/**
 * Normalized verb, e.g. 'connected_to'.
 */
export type Action1 = string;
/**
 * @maxItems 64
 */
export type Entities = EntityRef[];
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CanonicalKind".
 */
export type CanonicalKind = "network_flow" | "auth" | "dns" | "process_exec" | "file_access";
export type OccurredAt1 = string;
export type Outcome = string | null;
/**
 * The telemetry.raw event this was derived from (lineage).
 */
export type RawEventId1 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventType".
 */
export type EventType =
  | "telemetry.network_flow"
  | "telemetry.auth_event"
  | "telemetry.dns_query"
  | "telemetry.process_exec"
  | "telemetry.file_access"
  | "event.canonical"
  | "graph.command"
  | "graph.event"
  | "detection.raised"
  | "attack_chain.updated"
  | "ti.indicator_updated"
  | "agent.task"
  | "response.action"
  | "campaign.updated"
  | "report.generated"
  | "user.event";
export type DisplayName = string;
export type Email = string;
/**
 * System or tenant role names to grant on creation (audited).
 *
 * @maxItems 20
 */
export type RoleNames = string[];
export type Items = AttackChainModel[];
export type Limit = number;
export type NextCursor = string | null;
export type CreatedAt3 = string;
export type DedupKey = string;
export type Description2 = string;
/**
 * How a detection was produced.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DetectorKind".
 */
export type DetectorKind = "rule" | "statistical" | "isolation_forest" | "autoencoder" | "composite";
/**
 * @maxItems 64
 */
export type Entities1 = EntityRef[];
/**
 * What a single piece of detection evidence is.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EvidenceKind".
 */
export type EvidenceKind =
  "event" | "feature" | "rule_match" | "anomaly_score" | "threshold" | "graph_path" | "ti_indicator" | "technique";
/**
 * '<service>:<id>'.
 */
export type Provenance = string;
/**
 * Id / key of the evidence subject.
 */
export type Ref = string;
export type Summary = string;
/**
 * @maxItems 128
 */
export type Evidence = EvidenceItem[];
export type FirstSeen3 = string;
export type Id3 = string;
export type LastSeen3 = string;
export type RawEventId2 = string | null;
export type RuleId = string | null;
export type Score3 = number;
/**
 * Detection lifecycle (Constitution §17).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DetectionStatus".
 */
export type DetectionStatus = "new" | "triaged" | "confirmed" | "dismissed" | "suppressed";
/**
 * @maxItems 32
 */
export type TechniqueIds3 = string[];
export type TenantId4 = string;
export type Title = string;
export type UpdatedAt3 = string;
export type Items1 = Detection[];
export type Limit1 = number;
export type NextCursor1 = string | null;
export type AcknowledgedAt = string | null;
export type ClosedAt = string | null;
export type CreatedAt4 = string;
export type DetectionId = string;
export type Id4 = string;
export type OpenedAt = string;
export type Summary1 = string;
export type TenantId5 = string;
export type Title1 = string;
export type UpdatedAt4 = string;
export type Items2 = SecurityAlert[];
export type Limit2 = number;
export type NextCursor2 = string | null;
export type ComputedAt = string;
export type CreatedAt5 = string;
export type Id5 = string;
export type Score4 = number;
export type SubjectId2 = string;
export type TenantId6 = string;
export type UpdatedAt5 = string;
export type WeightsVersion = string;
export type Items3 = ThreatScore[];
export type Limit3 = number;
export type NextCursor3 = string | null;
/**
 * No secrets, no internals.
 */
export type Detail1 = string | null;
export type Healthy = boolean;
export type LatencyMs = number | null;
export type Name2 = string;
export type DedupKey1 = string;
/**
 * When detection-engine raised it. UTC.
 */
export type DetectedAt = string;
export type DetectionId1 = string;
/**
 * @maxItems 64
 */
export type Entities2 = EntityRef[];
export type EvidenceCount = number;
/**
 * Event time of the telemetry that triggered this. UTC.
 */
export type OccurredAt2 = string;
/**
 * Lineage to the canonical event.
 */
export type RawEventId3 = string | null;
export type RuleId1 = string | null;
/**
 * Composite threat score in [0,1].
 */
export type Score5 = number;
/**
 * Primary subject value.
 */
export type SubjectId3 = string | null;
/**
 * @maxItems 32
 */
export type TechniqueIds4 = string[];
export type TenantId7 = string;
export type Title2 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Direction".
 */
export type Direction = "inbound" | "outbound" | "lateral" | "unknown";
/**
 * @maxItems 64
 */
export type Answers = string[];
export type ClientHost = string | null;
export type ClientIp = string;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt3 = string;
export type QueryName = string;
/**
 * A, AAAA, CNAME, TXT, PTR, MX, …
 */
export type QueryType = string;
export type ResolverIp = string | null;
/**
 * NOERROR/NXDOMAIN/SERVFAIL/…
 */
export type ResponseCode = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "IndicatorFreshness".
 */
export type IndicatorFreshness = "fresh" | "aging" | "stale" | "expired";
export type ActorId1 = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiConfidence".
 */
export type TiConfidence = "low" | "medium" | "high";
export type CreatedAt6 = string;
export type ExpiresAt = string | null;
export type FirstSeen4 = string;
export type Id6 = string;
export type LastSeen4 = string;
/**
 * '<source>' or 'fixture:<name>'.
 */
export type Provider = string;
/**
 * URL / feed line / ticket id.
 */
export type Reference = string;
export type RetrievedAt = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiSourceKind".
 */
export type TiSourceKind = "feed" | "api" | "manual" | "fixture";
/**
 * Rule-derived, 1 = most malicious.
 */
export type Reputation = number;
export type Source1 = string;
/**
 * @maxItems 32
 */
export type Tags = string[];
/**
 * NULL = platform-global.
 */
export type TenantId8 = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "IndicatorType".
 */
export type IndicatorType = "ipv4" | "ipv6" | "domain" | "url" | "sha256" | "sha1" | "md5" | "email";
export type UpdatedAt6 = string;
/**
 * Normalized (normalize_indicator_value).
 */
export type Value1 = string;
export type Matched = boolean;
export type Value2 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorCode".
 */
export type ErrorCode =
  | "unauthenticated"
  | "invalid_credentials"
  | "permission_denied"
  | "tenant_forbidden"
  | "not_found"
  | "validation_error"
  | "conflict"
  | "rate_limited"
  | "dependency_unavailable"
  | "degraded_result"
  | "payload_too_large"
  | "unsupported_media_type"
  | "internal_error";
export type CorrelationId1 = string;
/**
 * Dotted path, e.g. 'body.email'.
 */
export type Field = string;
/**
 * Stable machine-readable issue slug.
 */
export type Issue = string;
export type Details = ErrorDetail[];
/**
 * Human-readable, safe to display, contains no internals.
 */
export type Message = string;
export type RequestId1 = string;
export type CorrelationId2 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt4 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer = string;
export type SensorId = string | null;
export type Site = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SourceType".
 */
export type SourceType = "sensor" | "deception" | "simulation" | "internal";
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId9 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId = string | null;
export type CorrelationId3 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId1 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion1 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt1 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt5 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey1 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer1 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId10 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId1 = string | null;
export type CorrelationId4 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId2 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion2 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt2 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt6 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey2 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer2 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId11 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId2 = string | null;
export type CorrelationId5 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId3 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion3 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt3 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt7 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey3 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer3 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId12 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId3 = string | null;
export type CorrelationId6 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId4 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion4 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt4 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt8 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey4 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer4 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId13 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId4 = string | null;
export type CorrelationId7 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId5 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion5 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt5 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt9 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey5 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "FileAction".
 */
export type FileAction = "read" | "write" | "create" | "delete" | "rename" | "execute" | "permission_change";
export type HashSha256 = string | null;
export type Host = string;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt10 = string;
export type Path = string;
export type ProcessId = number | null;
export type ProcessName = string | null;
export type User = string | null;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer5 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId14 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId5 = string | null;
export type CorrelationId8 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId6 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion6 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt6 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt11 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey6 = string;
/**
 * Idempotency key; deterministic per source event + command.
 */
export type CommandId = string;
/**
 * Neo4j label, e.g. ':Host'.
 */
export type Label = string;
export type Label1 = string;
/**
 * Event time from the source event. UTC.
 */
export type ObservedAt1 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphOp".
 */
export type GraphOp = "MERGE_NODE" | "MERGE_EDGE" | "SET_PROPS" | "PRUNE";
/**
 * The canonical/detection event this was derived from (lineage).
 */
export type RawEventId4 = string;
/**
 * Becomes a non-null property on every node/edge (data-model invariant).
 */
export type TenantId15 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer6 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId16 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId6 = string | null;
export type CorrelationId9 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId7 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion7 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt7 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt12 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey7 = string;
/**
 * The `graph.commands` command this reports on.
 */
export type CommandId1 = string;
/**
 * Node label or relationship type.
 */
export type Label2 = string;
export type NodesWritten = number;
/**
 * Event time carried from the command. UTC.
 */
export type ObservedAt2 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphMutationOutcome".
 */
export type GraphMutationOutcome = "APPLIED" | "DUPLICATE" | "STALE";
/**
 * Lineage — the source telemetry/detection event.
 */
export type RawEventId5 = string;
export type RelationshipsWritten = number;
export type TenantId17 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer7 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId18 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId7 = string | null;
export type CorrelationId10 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId8 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion8 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt8 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt13 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey8 = string;
/**
 * e.g. http, dns, ssh.
 */
export type AppProtocol = string | null;
export type BytesReceived = number;
export type BytesSent = number;
export type Direction1 = "inbound" | "outbound" | "lateral" | "unknown";
export type DstHost = string | null;
export type DstIp = string;
export type DstPort = number | null;
export type EndedAt = string | null;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt14 = string;
export type PacketsReceived = number;
export type PacketsSent = number;
/**
 * Transport, e.g. tcp/udp/icmp.
 */
export type Protocol = string;
export type SrcHost = string | null;
export type SrcIp = string;
export type SrcPort = number | null;
/**
 * Firewall/IDS verdict if any.
 */
export type Verdict = string | null;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer8 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId19 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId8 = string | null;
export type CorrelationId11 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId9 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion9 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt9 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt15 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey9 = string;
export type CommandLine = string | null;
export type HashSha2561 = string | null;
export type Host1 = string;
/**
 * Event time as observed by the sensor. UTC.
 */
export type OccurredAt16 = string;
export type ParentProcessId = number | null;
export type ParentProcessName = string | null;
export type ProcessId1 = number | null;
export type ProcessName1 = string;
export type ProcessPath = string | null;
export type Signed = boolean | null;
export type User1 = string | null;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer9 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId20 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId9 = string | null;
export type CorrelationId12 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId10 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion10 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt10 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt17 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey10 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiUpdateAction".
 */
export type TiUpdateAction = "added" | "updated" | "expired";
export type IndicatorId = string;
export type ObservedAt3 = string;
export type Source2 = string;
export type TenantId21 = string | null;
export type Value3 = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer10 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId22 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId10 = string | null;
export type CorrelationId13 = string;
/**
 * Globally unique, time-ordered (UUIDv7). Idempotency key.
 */
export type EventId11 = string;
/**
 * Schema version of `payload`.
 */
export type EventVersion11 = number;
/**
 * Set by ingestion-gateway on receipt. UTC.
 */
export type IngestedAt11 = string;
/**
 * Event time, from the source. UTC.
 */
export type OccurredAt18 = string;
/**
 * Derived (tenant + primary entity). Controls ordering.
 */
export type PartitionKey11 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserEventAction".
 */
export type UserEventAction =
  | "created"
  | "updated"
  | "disabled"
  | "role_granted"
  | "role_revoked"
  | "login_succeeded"
  | "login_failed"
  | "logged_out";
/**
 * Who performed the action; null for self-service/system.
 */
export type ActorId2 = string | null;
/**
 * Set for role_granted / role_revoked.
 */
export type RoleId = string | null;
export type UserId = string;
/**
 * `<service>@<semver>`, e.g. ingestion-gateway@0.1.0
 */
export type Producer11 = string;
/**
 * Set from the authenticated producer context, never trusted from input.
 */
export type TenantId23 = string;
/**
 * W3C trace-context trace-id.
 */
export type TraceId11 = string | null;
export type RoleId1 = string;
export type Dst = string;
export type Src = string;
export type Type = string;
export type Depth = number;
/**
 * @maxItems 20000
 */
export type Edges = GraphEdge[];
export type Id7 = string;
/**
 * @maxItems 32
 */
export type Labels = string[];
/**
 * @maxItems 5000
 */
export type Nodes = GraphNode[];
export type RootId = string;
export type Truncated = boolean;
/**
 * @maxItems 64
 */
export type Edges1 = GraphEdge[];
export type Found = boolean;
export type Length = number | null;
/**
 * @maxItems 64
 */
export type Nodes1 = GraphNode[];
export type Service = string;
export type Status = "ok";
export type Version1 = string;
export type Email1 = string;
export type Password = string;
export type TenantSlug = string;
/**
 * Deny-by-default: absence of a code means the action is forbidden.
 *
 * Phase 1 seeds the auth/admin subset. Later phases add their own codes; this
 * enum grows additively.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "PermissionCode".
 */
export type PermissionCode =
  | "users:read"
  | "users:create"
  | "users:update"
  | "roles:read"
  | "roles:grant"
  | "sensors:read"
  | "sensors:manage"
  | "audit:read"
  | "ops:read"
  | "detections:read"
  | "hunt:query"
  | "reports:generate"
  | "response:execute"
  | "response:approve";
/**
 * Effective permissions for this session, resolved server-side.
 */
export type Permissions = PermissionCode[];
export type SessionExpiresAt = string;
export type CreatedAt7 = string;
export type DisplayName1 = string;
export type Email2 = string;
/**
 * OIDC `sub` for federated users; null for local-only users.
 */
export type ExternalSubject = string | null;
export type Id8 = string;
export type LastLoginAt = string | null;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserStatus".
 */
export type UserStatus = "active" | "disabled" | "invited";
export type TenantId24 = string;
export type UpdatedAt7 = string;
export type Ok = boolean;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MappingConfidence".
 */
export type MappingConfidence = "low" | "medium" | "high";
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MappingSource".
 */
export type MappingSource = "rule" | "graph" | "feature" | "llm" | "analyst";
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MappingSubjectType".
 */
export type MappingSubjectType = "detection" | "attack_chain";
export type Permissions1 = PermissionCode[];
/**
 * Role names granted to the user.
 */
export type Roles = string[];
export type CreatedAt8 = string;
export type Id9 = string;
export type Name3 = string;
/**
 * URL-safe stable identifier, unique across the platform (3-40 chars, no leading/trailing hyphen).
 */
export type Slug = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TenantStatus".
 */
export type TenantStatus = "active" | "suspended";
export type UpdatedAt8 = string;
export type ApiVersion = string;
export type Build = string;
export type Environment = "local" | "ci" | "staging" | "production";
export type Service1 = string;
export type Name4 = string;
export type SubjectCount = number;
export type TacticId1 = string | null;
export type TechniqueId1 = string;
/**
 * @maxItems 1000
 */
export type Cells = MitreHeatmapCell[];
export type MatrixVersion2 = string | null;
export type Action2 = string;
export type Description3 = string;
export type Id10 = string;
export type ResourceType1 = string;
export type Dependencies = DepStatus[];
export type Ready = boolean;
export type ComputedAt1 = string;
export type Score6 = number;
export type SubjectId4 = string;
export type CreatedAt9 = string;
export type Description4 = string;
export type Id11 = string;
export type IsSystem = boolean;
export type Name5 = string;
export type TenantId25 = string | null;
export type UpdatedAt9 = string;
export type PermissionId = string;
export type RoleId2 = string;
export type Description5 = string;
export type Id12 = string;
export type IsSystem1 = boolean;
export type Name6 = string;
export type CreatedAt10 = string;
export type Id13 = string;
export type LastSeenAt = string | null;
export type Name7 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SensorStatus".
 */
export type SensorStatus = "active" | "disabled" | "pending";
export type TenantId26 = string;
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SensorType".
 */
export type SensorType = "network" | "auth" | "dns" | "process" | "file" | "mixed";
export type UpdatedAt10 = string;
export type ActiveChains = number;
export type Detections24H = number;
export type GeneratedAt = string;
export type OpenAlerts = number;
/**
 * @maxItems 20
 */
export type TopRiskSubjects = RiskSubject[];
export type CreatedAt11 = string;
/**
 * @maxItems 64
 */
export type Evidence1 = EvidenceItem[];
export type Id14 = string;
export type MatrixVersion3 = string;
export type Rationale = string;
export type SubjectId5 = string;
export type TacticId2 = string | null;
export type TechniqueId2 = string;
export type TenantId27 = string;
export type UpdatedAt11 = string;
export type MatrixVersion4 = string;
export type Name8 = string;
export type Rationale1 = string;
export type TacticId3 = string | null;
export type TacticName = string | null;
export type TechniqueId3 = string;
/**
 * Slug, e.g. 'apt29'.
 */
export type ActorId3 = string;
/**
 * @maxItems 32
 */
export type Aliases = string[];
export type CreatedAt12 = string;
export type Description6 = string;
export type FirstSeen5 = string | null;
export type Id15 = string;
export type LastSeen5 = string | null;
export type Name9 = string;
export type Source3 = string;
export type UpdatedAt12 = string;
export type ActorId4 = string | null;
export type CreatedAt13 = string;
export type Description7 = string;
export type FirstSeen6 = string | null;
export type Id16 = string;
export type LastSeen6 = string | null;
export type Name10 = string;
export type TenantId28 = string;
export type UpdatedAt13 = string;
export type CreatedAt14 = string;
export type Enabled = boolean;
export type Id17 = string;
export type IndicatorCount = number;
export type LastPollAt = string | null;
export type LastPollStatus = string | null;
export type Name11 = string;
/**
 * Fresh window; freshness derives from it.
 */
export type TtlSeconds = number;
export type UpdatedAt14 = string;
export type At = string;
export type Kind = string;
export type RefId = string;
export type Title3 = string;
/**
 * @maxItems 500
 */
export type Entries = TimelineEntry[];
export type SubjectId6 = string;
export type CreatedAt15 = string;
export type DisplayName2 = string;
export type Email3 = string;
/**
 * OIDC `sub` for federated users; null for local-only users.
 */
export type ExternalSubject1 = string | null;
export type Id18 = string;
export type LastLoginAt1 = string | null;
export type TenantId29 = string;
export type UpdatedAt15 = string;
export type GrantedAt = string;
export type GrantedBy = string;
export type RoleId3 = string;
export type UserId1 = string;

export interface SentinelMeshContracts {
  [k: string]: unknown;
}
/**
 * One scored feature vector. An anomaly is *evidence*, not a conclusion.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Anomaly".
 */
export interface Anomaly {
  created_at: CreatedAt;
  entity?: EntityRef | null;
  feature_schema_version: FeatureSchemaVersion;
  features?: Features;
  id: Id;
  is_anomaly: IsAnomaly;
  method: AnomalyMethod;
  model_version?: ModelVersion;
  normalized_score: NormalizedScore;
  observed_at: ObservedAt;
  raw_event_id?: RawEventId;
  score: Score;
  tenant_id: TenantId;
  threshold: Threshold;
  updated_at: UpdatedAt;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EntityRef".
 */
export interface EntityRef {
  kind: EntityKind;
  value: Value;
}
export interface Features {
  [k: string]: number;
}
/**
 * The full chain as returned by `correlation-engine`'s read API.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackChainModel".
 */
export interface AttackChainModel {
  confidence: Confidence;
  created_at: CreatedAt1;
  detection_count: DetectionCount;
  distinct_stage_count: DistinctStageCount;
  first_seen: FirstSeen;
  id: Id1;
  last_seen: LastSeen;
  notes?: Notes;
  progression: Progression;
  score: Score1;
  score_version: ScoreVersion;
  scoring_status: ScoringStatus;
  stages?: Stages;
  status: ChainStatus;
  subject_id: SubjectId;
  subject_type: ThreatSubjectType;
  technique_ids?: TechniqueIds1;
  tenant_id: TenantId1;
  ti_corroborated?: TiCorroborated;
  updated_at: UpdatedAt1;
  window_start: WindowStart;
}
/**
 * One kill-chain stage within a chain, with the detections behind it.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ChainStageModel".
 */
export interface ChainStageModel {
  detection_count: DetectionCount1;
  detection_ids?: DetectionIds;
  first_seen: FirstSeen1;
  last_seen: LastSeen1;
  max_detection_score: MaxDetectionScore;
  max_severity: Severity;
  stage: AttackStage;
  stage_order: StageOrder;
  technique_ids?: TechniqueIds;
}
/**
 * `attack_chains` topic event (`EventType.attack_chain_updated`).
 *
 * Thin projection: enough to render a chain row and to fan a notification out.
 * The per-stage evidence stays in Postgres.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackChainPayload".
 */
export interface AttackChainPayload {
  chain_id: ChainId;
  confidence: Confidence1;
  detection_count: DetectionCount2;
  distinct_stage_count: DistinctStageCount1;
  first_seen: FirstSeen2;
  last_seen: LastSeen2;
  latest_stage: AttackStage;
  progression: Progression1;
  score: Score2;
  score_version: ScoreVersion1;
  scoring_status: ScoringStatus;
  stage_count: StageCount;
  status: ChainStatus;
  subject_id: SubjectId1;
  subject_type: ThreatSubjectType;
  technique_ids?: TechniqueIds2;
  tenant_id: TenantId2;
  ti_corroborated?: TiCorroborated1;
  updated_at: UpdatedAt2;
}
/**
 * What one import run actually produced. Coverage claims read from here.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackMatrixVersion".
 */
export interface AttackMatrixVersion {
  imported_at: ImportedAt;
  source: Source;
  stix_bundle_sha256: StixBundleSha256;
  subtechnique_count: SubtechniqueCount;
  tactic_count: TacticCount;
  technique_count: TechniqueCount;
  version: Version;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackTactic".
 */
export interface AttackTactic {
  description?: Description;
  matrix_version: MatrixVersion;
  name: Name;
  shortname: Shortname;
  tactic_id: TacticId;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AttackTechnique".
 */
export interface AttackTechnique {
  deprecated?: Deprecated;
  description?: Description1;
  is_subtechnique?: IsSubtechnique;
  matrix_version: MatrixVersion1;
  name: Name1;
  parent_technique_id?: ParentTechniqueId;
  tactic_ids?: TacticIds;
  technique_id: TechniqueId;
}
/**
 * Append-only audit entry (safe DTO).
 *
 * The storage row additionally carries per-tenant hash-chain columns
 * (`prev_hash`, `hash`) which are an integrity mechanism, not part of the
 * contract.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuditRecord".
 */
export interface AuditRecord {
  action: Action;
  actor_id?: ActorId;
  actor_type: ActorType;
  correlation_id?: CorrelationId;
  created_at: CreatedAt2;
  id: Id2;
  ip?: Ip;
  metadata?: Metadata;
  request_id?: RequestId;
  resource_id?: ResourceId;
  resource_type: ResourceType;
  result: AuditResult;
  tenant_id?: TenantId3;
}
export interface Metadata {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "AuthEventPayload".
 */
export interface AuthEventPayload {
  auth_type: AuthType;
  failure_reason?: FailureReason;
  logon_id?: LogonId;
  occurred_at: OccurredAt;
  outcome: AuthOutcome;
  principal: Principal;
  source_host?: SourceHost;
  source_ip?: SourceIp;
  target_host?: TargetHost;
}
/**
 * The normalized view of one telemetry event. Written by
 * `normalization-engine`, consumed by the graph, detection and memory
 * subsystems.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CanonicalEventPayload".
 */
export interface CanonicalEventPayload {
  action: Action1;
  /**
   * Entity that initiated the event.
   */
  actor?: EntityRef | null;
  attributes?: Attributes;
  enrichment?: Enrichment;
  entities?: Entities;
  kind: CanonicalKind;
  occurred_at: OccurredAt1;
  outcome?: Outcome;
  raw_event_id: RawEventId1;
  raw_event_type: EventType;
  /**
   * Entity acted upon.
   */
  target?: EntityRef | null;
}
/**
 * Normalized flat attributes (ports, bytes, query name, …).
 */
export interface Attributes {
  [k: string]: unknown;
}
/**
 * Enrichment results keyed by provider, each carrying its own provenance and freshness. Absent or partial when a provider was unavailable.
 */
export interface Enrichment {
  [k: string]: unknown;
}
/**
 * Invite/create a user inside the caller's tenant.
 *
 * `tenant_id` is intentionally absent: the server uses the authenticated
 * caller's tenant. Accepting a client-supplied tenant here would be a
 * tenant-injection / mass-assignment flaw (Engineering Constitution §5, §6).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CreateUserRequest".
 */
export interface CreateUserRequest {
  display_name: DisplayName;
  email: Email;
  role_names?: RoleNames;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_AttackChain".
 */
export interface CursorPageAttackChainModel {
  items: Items;
  limit: Limit;
  next_cursor?: NextCursor;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_Detection".
 */
export interface CursorPageDetection {
  items: Items1;
  limit: Limit1;
  next_cursor?: NextCursor1;
}
/**
 * A finding. Every claim it makes is backed by an item in `evidence`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Detection".
 */
export interface Detection {
  created_at: CreatedAt3;
  dedup_key: DedupKey;
  description?: Description2;
  detector: DetectorKind;
  entities?: Entities1;
  evidence?: Evidence;
  first_seen: FirstSeen3;
  id: Id3;
  last_seen: LastSeen3;
  raw_event_id?: RawEventId2;
  rule_id?: RuleId;
  score: Score3;
  scoring_status: ScoringStatus;
  severity: Severity;
  status: DetectionStatus;
  technique_ids?: TechniqueIds3;
  tenant_id: TenantId4;
  title: Title;
  updated_at: UpdatedAt3;
}
/**
 * One grounded fact behind a detection. `provenance` is `<service>:<id>` so a
 * reader can chase every claim back to its source.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EvidenceItem".
 */
export interface EvidenceItem {
  detail?: Detail;
  kind: EvidenceKind;
  provenance: Provenance;
  ref: Ref;
  summary: Summary;
}
export interface Detail {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_SecurityAlert".
 */
export interface CursorPageSecurityAlert {
  items: Items2;
  limit: Limit2;
  next_cursor?: NextCursor2;
}
/**
 * Raised from a `Detection` that crosses the alerting threshold. The analyst-
 * facing lifecycle object.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SecurityAlert".
 */
export interface SecurityAlert {
  acknowledged_at?: AcknowledgedAt;
  closed_at?: ClosedAt;
  created_at: CreatedAt4;
  detection_id: DetectionId;
  id: Id4;
  opened_at: OpenedAt;
  severity: Severity;
  status: AlertStatus;
  summary?: Summary1;
  tenant_id: TenantId5;
  title: Title1;
  updated_at: UpdatedAt4;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "CursorPage_ThreatScore".
 */
export interface CursorPageThreatScore {
  items: Items3;
  limit: Limit3;
  next_cursor?: NextCursor3;
}
/**
 * A deterministic composite score for one subject. `components` + `weights_version`
 * make it fully reproducible.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatScore".
 */
export interface ThreatScore {
  components: Components;
  computed_at: ComputedAt;
  created_at: CreatedAt5;
  id: Id5;
  score: Score4;
  scoring_status: ScoringStatus;
  subject_id: SubjectId2;
  subject_type: ThreatSubjectType;
  tenant_id: TenantId6;
  updated_at: UpdatedAt5;
  weights_version: WeightsVersion;
}
/**
 * Named contributions before weighting.
 */
export interface Components {
  [k: string]: number;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DepStatus".
 */
export interface DepStatus {
  detail?: Detail1;
  healthy: Healthy;
  latency_ms?: LatencyMs;
  name: Name2;
}
/**
 * `detections` topic event — the thin projection of a Postgres `detection`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DetectionPayload".
 */
export interface DetectionPayload {
  dedup_key: DedupKey1;
  detected_at: DetectedAt;
  detection_id: DetectionId1;
  detector: DetectorKind;
  entities?: Entities2;
  evidence_count: EvidenceCount;
  occurred_at: OccurredAt2;
  raw_event_id?: RawEventId3;
  rule_id?: RuleId1;
  score: Score5;
  scoring_status: ScoringStatus;
  severity: Severity;
  subject_id?: SubjectId3;
  /**
   * Primary subject of the finding (for correlation into attack chains).
   */
  subject_type?: ThreatSubjectType | null;
  technique_ids?: TechniqueIds4;
  tenant_id: TenantId7;
  title: Title2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "DnsQueryPayload".
 */
export interface DnsQueryPayload {
  answers?: Answers;
  client_host?: ClientHost;
  client_ip: ClientIp;
  occurred_at: OccurredAt3;
  query_name: QueryName;
  query_type: QueryType;
  resolver_ip?: ResolverIp;
  response_code?: ResponseCode;
}
/**
 * One result of the enrichment API — was `{type, value}` a known indicator?
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EnrichmentMatch".
 */
export interface EnrichmentMatch {
  freshness?: IndicatorFreshness | null;
  indicator?: ThreatIndicator | null;
  matched: Matched;
  type: IndicatorType;
  value: Value2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatIndicator".
 */
export interface ThreatIndicator {
  actor_id?: ActorId1;
  confidence: TiConfidence;
  created_at: CreatedAt6;
  expires_at?: ExpiresAt;
  first_seen: FirstSeen4;
  freshness: IndicatorFreshness;
  id: Id6;
  last_seen: LastSeen4;
  provenance: Provenance1;
  reputation: Reputation;
  source: Source1;
  tags?: Tags;
  tenant_id?: TenantId8;
  type: IndicatorType;
  updated_at: UpdatedAt6;
  value: Value1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Provenance".
 */
export interface Provenance1 {
  provider: Provider;
  reference?: Reference;
  retrieved_at: RetrievedAt;
  source_kind: TiSourceKind;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  code: ErrorCode;
  correlation_id: CorrelationId1;
  details?: Details;
  message: Message;
  request_id: RequestId1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorDetail".
 */
export interface ErrorDetail {
  field: Field;
  issue: Issue;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_AttackChain".
 */
export interface EventEnvelopeAttackChainPayload {
  correlation_id: CorrelationId2;
  event_id: EventId;
  event_type: EventType;
  event_version: EventVersion;
  ingested_at: IngestedAt;
  metadata?: Metadata1;
  occurred_at: OccurredAt4;
  partition_key: PartitionKey;
  payload: AttackChainPayload;
  producer: Producer;
  source: EventSource;
  tenant_id: TenantId9;
  trace_id?: TraceId;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventSource".
 */
export interface EventSource {
  sensor_id?: SensorId;
  site?: Site;
  type: SourceType;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_AuthEvent".
 */
export interface EventEnvelopeAuthEventPayload {
  correlation_id: CorrelationId3;
  event_id: EventId1;
  event_type: EventType;
  event_version: EventVersion1;
  ingested_at: IngestedAt1;
  metadata?: Metadata2;
  occurred_at: OccurredAt5;
  partition_key: PartitionKey1;
  payload: AuthEventPayload;
  producer: Producer1;
  source: EventSource;
  tenant_id: TenantId10;
  trace_id?: TraceId1;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata2 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_CanonicalEvent".
 */
export interface EventEnvelopeCanonicalEventPayload {
  correlation_id: CorrelationId4;
  event_id: EventId2;
  event_type: EventType;
  event_version: EventVersion2;
  ingested_at: IngestedAt2;
  metadata?: Metadata3;
  occurred_at: OccurredAt6;
  partition_key: PartitionKey2;
  payload: CanonicalEventPayload;
  producer: Producer2;
  source: EventSource;
  tenant_id: TenantId11;
  trace_id?: TraceId2;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata3 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_Detection".
 */
export interface EventEnvelopeDetectionPayload {
  correlation_id: CorrelationId5;
  event_id: EventId3;
  event_type: EventType;
  event_version: EventVersion3;
  ingested_at: IngestedAt3;
  metadata?: Metadata4;
  occurred_at: OccurredAt7;
  partition_key: PartitionKey3;
  payload: DetectionPayload;
  producer: Producer3;
  source: EventSource;
  tenant_id: TenantId12;
  trace_id?: TraceId3;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata4 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_DnsQuery".
 */
export interface EventEnvelopeDnsQueryPayload {
  correlation_id: CorrelationId6;
  event_id: EventId4;
  event_type: EventType;
  event_version: EventVersion4;
  ingested_at: IngestedAt4;
  metadata?: Metadata5;
  occurred_at: OccurredAt8;
  partition_key: PartitionKey4;
  payload: DnsQueryPayload;
  producer: Producer4;
  source: EventSource;
  tenant_id: TenantId13;
  trace_id?: TraceId4;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata5 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_FileAccess".
 */
export interface EventEnvelopeFileAccessPayload {
  correlation_id: CorrelationId7;
  event_id: EventId5;
  event_type: EventType;
  event_version: EventVersion5;
  ingested_at: IngestedAt5;
  metadata?: Metadata6;
  occurred_at: OccurredAt9;
  partition_key: PartitionKey5;
  payload: FileAccessPayload;
  producer: Producer5;
  source: EventSource;
  tenant_id: TenantId14;
  trace_id?: TraceId5;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata6 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "FileAccessPayload".
 */
export interface FileAccessPayload {
  action: FileAction;
  hash_sha256?: HashSha256;
  host: Host;
  occurred_at: OccurredAt10;
  path: Path;
  process_id?: ProcessId;
  process_name?: ProcessName;
  user?: User;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_GraphCommand".
 */
export interface EventEnvelopeGraphCommandPayload {
  correlation_id: CorrelationId8;
  event_id: EventId6;
  event_type: EventType;
  event_version: EventVersion6;
  ingested_at: IngestedAt6;
  metadata?: Metadata7;
  occurred_at: OccurredAt11;
  partition_key: PartitionKey6;
  payload: GraphCommandPayload;
  producer: Producer6;
  source: EventSource;
  tenant_id: TenantId16;
  trace_id?: TraceId6;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata7 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphCommandPayload".
 */
export interface GraphCommandPayload {
  command_id: CommandId;
  end?: GraphEndpoint | null;
  key?: Key1;
  label: Label1;
  observed_at: ObservedAt1;
  op: GraphOp;
  props?: Props;
  raw_event_id: RawEventId4;
  start?: GraphEndpoint | null;
  tenant_id: TenantId15;
}
/**
 * One end of a `MERGE_EDGE` — a node label plus its key.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphEndpoint".
 */
export interface GraphEndpoint {
  key: Key;
  label: Label;
}
/**
 * The node's key property, e.g. {'host_id': 'web01'}.
 */
export interface Key {
  [k: string]: unknown;
}
/**
 * For a node op: its key property. For MERGE_EDGE: unused (see start/end).
 */
export interface Key1 {
  [k: string]: unknown;
}
export interface Props {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_GraphEvent".
 */
export interface EventEnvelopeGraphEventPayload {
  correlation_id: CorrelationId9;
  event_id: EventId7;
  event_type: EventType;
  event_version: EventVersion7;
  ingested_at: IngestedAt7;
  metadata?: Metadata8;
  occurred_at: OccurredAt12;
  partition_key: PartitionKey7;
  payload: GraphEventPayload;
  producer: Producer7;
  source: EventSource;
  tenant_id: TenantId18;
  trace_id?: TraceId7;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata8 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphEventPayload".
 */
export interface GraphEventPayload {
  command_id: CommandId1;
  label: Label2;
  nodes_written?: NodesWritten;
  observed_at: ObservedAt2;
  op: GraphOp;
  outcome: GraphMutationOutcome;
  raw_event_id: RawEventId5;
  relationships_written?: RelationshipsWritten;
  tenant_id: TenantId17;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_NetworkFlow".
 */
export interface EventEnvelopeNetworkFlowPayload {
  correlation_id: CorrelationId10;
  event_id: EventId8;
  event_type: EventType;
  event_version: EventVersion8;
  ingested_at: IngestedAt8;
  metadata?: Metadata9;
  occurred_at: OccurredAt13;
  partition_key: PartitionKey8;
  payload: NetworkFlowPayload;
  producer: Producer8;
  source: EventSource;
  tenant_id: TenantId19;
  trace_id?: TraceId8;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata9 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "NetworkFlowPayload".
 */
export interface NetworkFlowPayload {
  app_protocol?: AppProtocol;
  bytes_received?: BytesReceived;
  bytes_sent?: BytesSent;
  direction?: Direction1;
  dst_host?: DstHost;
  dst_ip: DstIp;
  dst_port?: DstPort;
  ended_at?: EndedAt;
  occurred_at: OccurredAt14;
  packets_received?: PacketsReceived;
  packets_sent?: PacketsSent;
  protocol: Protocol;
  src_host?: SrcHost;
  src_ip: SrcIp;
  src_port?: SrcPort;
  verdict?: Verdict;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_ProcessExec".
 */
export interface EventEnvelopeProcessExecPayload {
  correlation_id: CorrelationId11;
  event_id: EventId9;
  event_type: EventType;
  event_version: EventVersion9;
  ingested_at: IngestedAt9;
  metadata?: Metadata10;
  occurred_at: OccurredAt15;
  partition_key: PartitionKey9;
  payload: ProcessExecPayload;
  producer: Producer9;
  source: EventSource;
  tenant_id: TenantId20;
  trace_id?: TraceId9;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata10 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ProcessExecPayload".
 */
export interface ProcessExecPayload {
  command_line?: CommandLine;
  hash_sha256?: HashSha2561;
  host: Host1;
  occurred_at: OccurredAt16;
  parent_process_id?: ParentProcessId;
  parent_process_name?: ParentProcessName;
  process_id?: ProcessId1;
  process_name: ProcessName1;
  process_path?: ProcessPath;
  signed?: Signed;
  user?: User1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_TiUpdate".
 */
export interface EventEnvelopeTiUpdatePayload {
  correlation_id: CorrelationId12;
  event_id: EventId10;
  event_type: EventType;
  event_version: EventVersion10;
  ingested_at: IngestedAt10;
  metadata?: Metadata11;
  occurred_at: OccurredAt17;
  partition_key: PartitionKey10;
  payload: TiUpdatePayload;
  producer: Producer10;
  source: EventSource;
  tenant_id: TenantId22;
  trace_id?: TraceId10;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata11 {
  [k: string]: unknown;
}
/**
 * `ti.updates` topic event (`EventType.ti_indicator_updated`).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiUpdatePayload".
 */
export interface TiUpdatePayload {
  action: TiUpdateAction;
  confidence: TiConfidence;
  freshness: IndicatorFreshness;
  indicator_id: IndicatorId;
  observed_at: ObservedAt3;
  source: Source2;
  tenant_id?: TenantId21;
  type: IndicatorType;
  value: Value3;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "EventEnvelope_UserEvent".
 */
export interface EventEnvelopeUserEventPayload {
  correlation_id: CorrelationId13;
  event_id: EventId11;
  event_type: EventType;
  event_version: EventVersion11;
  ingested_at: IngestedAt11;
  metadata?: Metadata12;
  occurred_at: OccurredAt18;
  partition_key: PartitionKey11;
  payload: UserEventPayload;
  producer: Producer11;
  source: EventSource;
  tenant_id: TenantId23;
  trace_id?: TraceId11;
}
/**
 * Non-authoritative annotations (enrichment provenance, tags).
 */
export interface Metadata12 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserEventPayload".
 */
export interface UserEventPayload {
  action: UserEventAction;
  actor_id?: ActorId2;
  role_id?: RoleId;
  user_id: UserId;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GrantRoleRequest".
 */
export interface GrantRoleRequest {
  role_id: RoleId1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphEdge".
 */
export interface GraphEdge {
  dst: Dst;
  properties?: Properties;
  src: Src;
  type: Type;
}
export interface Properties {
  [k: string]: unknown;
}
/**
 * A bounded, tenant-scoped neighbourhood around one root node.
 *
 * `truncated` is true when the server row cap was hit — the view is partial and
 * the UI must say so rather than implying the entity has no other neighbours.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphNeighborhood".
 */
export interface GraphNeighborhood {
  depth: Depth;
  edges?: Edges;
  nodes?: Nodes;
  root_id: RootId;
  truncated?: Truncated;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphNode".
 */
export interface GraphNode {
  id: Id7;
  labels?: Labels;
  properties?: Properties1;
}
export interface Properties1 {
  [k: string]: unknown;
}
/**
 * The shortest path between two nodes, or `found=False` when there is none.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "GraphPath".
 */
export interface GraphPath {
  edges?: Edges1;
  found: Found;
  length?: Length;
  nodes?: Nodes1;
}
/**
 * `GET /healthz` — liveness. The process is up and can serve.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "HealthResponse".
 */
export interface HealthResponse {
  service: Service;
  status?: Status;
  version: Version1;
}
/**
 * Local fallback login. Federated users authenticate via OIDC instead.
 *
 * `tenant_slug` disambiguates the account; the server still resolves the tenant
 * server-side and never trusts a tenant id from the client.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "LoginRequest".
 */
export interface LoginRequest {
  email: Email1;
  password: Password;
  tenant_slug: TenantSlug;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "LoginResponse".
 */
export interface LoginResponse {
  permissions: Permissions;
  session_expires_at: SessionExpiresAt;
  user: User2;
}
/**
 * Safe user DTO.
 *
 * Security state (`password_hash`, `failed_login_count`, `locked_until`) lives
 * only in the api-gateway database model and is never serialized in a contract.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "User".
 */
export interface User2 {
  created_at: CreatedAt7;
  display_name: DisplayName1;
  email: Email2;
  external_subject?: ExternalSubject;
  id: Id8;
  last_login_at?: LastLoginAt;
  status: UserStatus;
  tenant_id: TenantId24;
  updated_at: UpdatedAt7;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "LogoutResponse".
 */
export interface LogoutResponse {
  ok?: Ok;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MeResponse".
 */
export interface MeResponse {
  permissions: Permissions1;
  roles: Roles;
  tenant: Tenant;
  user: User2;
}
/**
 * An isolated customer organization — the root of all data scoping.
 *
 * `Tenant` itself is not tenant-scoped.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Tenant".
 */
export interface Tenant {
  created_at: CreatedAt8;
  id: Id9;
  name: Name3;
  settings?: Settings;
  slug: Slug;
  status: TenantStatus;
  updated_at: UpdatedAt8;
}
export interface Settings {
  [k: string]: unknown;
}
/**
 * `GET /api/v1/meta` — non-sensitive build/runtime info.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MetaResponse".
 */
export interface MetaResponse {
  api_version: ApiVersion;
  build: Build;
  environment: Environment;
  service: Service1;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MitreHeatmap".
 */
export interface MitreHeatmap {
  cells?: Cells;
  matrix_version?: MatrixVersion2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "MitreHeatmapCell".
 */
export interface MitreHeatmapCell {
  name?: Name4;
  subject_count: SubjectCount;
  tactic_id?: TacticId1;
  technique_id: TechniqueId1;
}
/**
 * An atomic capability. Seeded and immutable; deny-by-default.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Permission".
 */
export interface Permission {
  action: Action2;
  code: PermissionCode;
  description: Description3;
  id: Id10;
  resource_type: ResourceType1;
}
/**
 * `GET /readyz` — readiness. `ready` is false if any *required* dependency
 * is unreachable; the service should then be pulled from rotation.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ReadyResponse".
 */
export interface ReadyResponse {
  dependencies?: Dependencies;
  ready: Ready;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RiskSubject".
 */
export interface RiskSubject {
  computed_at: ComputedAt1;
  score: Score6;
  scoring_status: ScoringStatus;
  subject_id: SubjectId4;
  subject_type: ThreatSubjectType;
}
/**
 * A named bundle of permissions.
 *
 * `tenant_id is None` marks a system role (same definition for every tenant).
 * A tenant-scoped role has a concrete `tenant_id`.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Role".
 */
export interface Role {
  created_at: CreatedAt9;
  description: Description4;
  id: Id11;
  is_system: IsSystem;
  name: Name5;
  tenant_id?: TenantId25;
  updated_at: UpdatedAt9;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RolePermission".
 */
export interface RolePermission {
  permission_id: PermissionId;
  role_id: RoleId2;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "RoleSummary".
 */
export interface RoleSummary {
  description: Description5;
  id: Id12;
  is_system: IsSystem1;
  name: Name6;
}
/**
 * A machine identity that emits telemetry for exactly one tenant.
 *
 * The sensor's `tenant_id` is authoritative for every event it produces; the
 * ingestion path overwrites any tenant value in an inbound payload with this
 * (Engineering Constitution §6).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "Sensor".
 */
export interface Sensor {
  created_at: CreatedAt10;
  id: Id13;
  last_seen_at?: LastSeenAt;
  name: Name7;
  status: SensorStatus;
  tenant_id: TenantId26;
  type: SensorType;
  updated_at: UpdatedAt10;
}
/**
 * The dashboard's top-of-page counters. Every number is a real row count for
 * the caller's tenant — never a fabricated figure.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "SocSummary".
 */
export interface SocSummary {
  active_chains: ActiveChains;
  alerts_by_severity?: AlertsBySeverity;
  detections_24h: Detections24H;
  generated_at: GeneratedAt;
  open_alerts: OpenAlerts;
  top_risk_subjects?: TopRiskSubjects;
}
export interface AlertsBySeverity {
  [k: string]: number;
}
/**
 * A persisted subject→technique mapping (Postgres `technique_mapping`).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TechniqueMapping".
 */
export interface TechniqueMapping {
  confidence: MappingConfidence;
  created_at: CreatedAt11;
  evidence?: Evidence1;
  id: Id14;
  matrix_version: MatrixVersion3;
  rationale: Rationale;
  source: MappingSource;
  subject_id: SubjectId5;
  subject_type: MappingSubjectType;
  tactic_id?: TacticId2;
  technique_id: TechniqueId2;
  tenant_id: TenantId27;
  updated_at: UpdatedAt11;
}
/**
 * One result of the mapping API — a candidate technique for a behaviour.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TechniqueMatch".
 */
export interface TechniqueMatch {
  confidence: MappingConfidence;
  matrix_version: MatrixVersion4;
  name: Name8;
  rationale: Rationale1;
  source: MappingSource;
  tactic_id?: TacticId3;
  tactic_name?: TacticName;
  technique_id: TechniqueId3;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "ThreatActor".
 */
export interface ThreatActor {
  actor_id: ActorId3;
  aliases?: Aliases;
  created_at: CreatedAt12;
  description?: Description6;
  first_seen?: FirstSeen5;
  id: Id15;
  last_seen?: LastSeen5;
  name: Name9;
  source: Source3;
  updated_at: UpdatedAt12;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiCampaign".
 */
export interface TiCampaign {
  actor_id?: ActorId4;
  created_at: CreatedAt13;
  description?: Description7;
  first_seen?: FirstSeen6;
  id: Id16;
  last_seen?: LastSeen6;
  name: Name10;
  tenant_id: TenantId28;
  updated_at: UpdatedAt13;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TiSource".
 */
export interface TiSource {
  created_at: CreatedAt14;
  enabled: Enabled;
  id: Id17;
  indicator_count?: IndicatorCount;
  kind: TiSourceKind;
  last_poll_at?: LastPollAt;
  last_poll_status?: LastPollStatus;
  name: Name11;
  ttl_seconds: TtlSeconds;
  updated_at: UpdatedAt14;
}
/**
 * One point on an entity's timeline — a detection, an alert transition, or a
 * chain-stage advance. `kind` distinguishes them for the UI.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TimelineEntry".
 */
export interface TimelineEntry {
  at: At;
  detail?: Detail2;
  kind: Kind;
  ref_id: RefId;
  severity?: Severity | null;
  title: Title3;
}
export interface Detail2 {
  [k: string]: string;
}
/**
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "TimelineResponse".
 */
export interface TimelineResponse {
  entries?: Entries;
  subject_id: SubjectId6;
  subject_type: ThreatSubjectType;
}
/**
 * Response alias for `User` — kept as an explicit type so the API surface is
 * named independently of the internal entity.
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserResponse".
 */
export interface UserResponse {
  created_at: CreatedAt15;
  display_name: DisplayName2;
  email: Email3;
  external_subject?: ExternalSubject1;
  id: Id18;
  last_login_at?: LastLoginAt1;
  status: UserStatus;
  tenant_id: TenantId29;
  updated_at: UpdatedAt15;
}
/**
 * A role assignment. Roles are only ever added via this record — there is no
 * request field anywhere that can grant a role or permission
 * (Engineering Constitution §5, §6: role-escalation prevention).
 *
 * This interface was referenced by `SentinelMeshContracts`'s JSON-Schema
 * via the `definition` "UserRoleGrant".
 */
export interface UserRoleGrant {
  granted_at: GrantedAt;
  granted_by: GrantedBy;
  role_id: RoleId3;
  user_id: UserId1;
}
