"""The grounded incident analyst.

Contract: the analyst answers **only** from the evidence in the request, every
sentence of the summary cites an evidence `ref`, and the analyst takes no action
and holds no tools. When no live LLM is reachable — or when the model's output
fails grounding validation — it returns a deterministic factual template with
`degraded = true`. It never invents a narrative.

Remediation `recommendations` are a fixed, vetted list per subject type — never
generated by the model — so a prompt injection cannot turn them into an action.
"""

from __future__ import annotations

import asyncio
import re
from collections.abc import Awaitable, Callable

from sm_ai import (
    AiError,
    ContextPoisoningDetected,
    EvidenceBuilder,
    EvidenceBundle,
    LlmClient,
    LlmMessage,
    LlmRequest,
    MessageRole,
    build_grounded_messages,
)
from sm_common.clock import utcnow
from sm_contracts import AnalystModelInfo, ExplainRequest, Explanation

__all__ = ["IncidentAnalyst"]

_CITE = re.compile(r"\[([A-Za-z0-9:_.\-]{1,96})\]")

_TASK_PROMPT = {
    "summarize": "Summarise what happened, in 3-6 sentences. Facts only.",
    "triage": "Assess severity and urgency for a SOC queue. State what makes this "
    "more or less urgent, from the evidence.",
    "reason": "Explain the likely sequence of events and what each piece of evidence "
    "contributes. Mark anything uncertain as uncertain.",
    "remediate": "Explain what a responder needs to understand before acting. Do not "
    "instruct any action yourself.",
}

_RECOMMENDATIONS: dict[str, list[str]] = {
    "detection": [
        "Confirm the detection against the raw events it cites before acting.",
        "Check whether the same rule fired for related entities in the last 24h.",
        "If credential abuse is indicated, review the account's recent sessions.",
    ],
    "attack_chain": [
        "Review each stage's supporting detections in order.",
        "Identify the earliest stage and scope containment from there.",
        "Confirm whether the chain spans more than one tenant asset.",
    ],
    "incident": [
        "Establish a single owner and a timeline before making changes.",
        "Preserve volatile evidence (memory, sessions) before isolation.",
        "Escalate per the tenant's runbook if the blast radius is unclear.",
    ],
}


class IncidentAnalyst:
    def __init__(
        self,
        llm: LlmClient | None,
        *,
        model: str,
        max_output_tokens: int,
        max_context_chars: int = 40_000,
        audit: Callable[[str], Awaitable[None]] | Callable[[str], None] | None = None,
    ) -> None:
        self._llm = llm
        self._model = model
        self._max_out = max_output_tokens
        self._max_context = max_context_chars
        self._audit = audit

    async def explain(self, req: ExplainRequest) -> Explanation:
        builder = EvidenceBuilder(max_total_chars=self._max_context)
        for e in req.evidence:
            builder.add(e.kind, e.ref, e.provenance, e.content, trusted=e.trusted)
        try:
            bundle = builder.build()
        except ContextPoisoningDetected:
            # Rebuild with only the trusted items so we can still say something.
            trimmed = EvidenceBuilder(max_total_chars=self._max_context)
            for e in req.evidence:
                if e.trusted:
                    trimmed.add(e.kind, e.ref, e.provenance, e.content, trusted=True)
            bundle = trimmed.build()
            return self._template(req, bundle, "context_rejected", evidence_flagged=True)

        flagged = bundle.has_flagged_content
        if flagged:
            await self._emit("evidence_flagged_injection")

        if self._llm is None:
            return self._template(req, bundle, "llm_disabled", evidence_flagged=flagged)

        task_text = _TASK_PROMPT.get(req.task, _TASK_PROMPT["summarize"])
        messages = list(build_grounded_messages(task_text, bundle))
        valid_refs = set(bundle.refs())

        for attempt in (1, 2):
            try:
                resp = await self._llm.complete(
                    LlmRequest(
                        model=self._model,
                        messages=tuple(messages),
                        max_completion_tokens=self._max_out,
                        purpose=f"analyst.{req.task}",
                    )
                )
            except AiError as exc:
                await self._emit(f"llm_error:{type(exc).__name__}")
                return self._template(
                    req, bundle, f"llm_error:{type(exc).__name__}", evidence_flagged=flagged
                )

            cited = _CITE.findall(resp.text)
            grounded = bool(cited) and set(cited) <= valid_refs
            if grounded:
                return Explanation(
                    subject_type=req.subject_type,
                    subject_id=req.subject_id,
                    summary=resp.text.strip(),
                    cited_refs=sorted(set(cited)),
                    confidence=self._confidence(resp.from_live_provider, flagged, len(set(cited))),
                    recommendations=_RECOMMENDATIONS.get(req.subject_type, []),
                    model=AnalystModelInfo(
                        provider=resp.provider,
                        model_id=resp.model,
                        prompt_sha256="",
                        from_live_provider=resp.from_live_provider,
                    ),
                    generated_at=utcnow(),
                    degraded=False,
                    evidence_flagged=flagged,
                )

            if attempt == 1:
                messages.append(
                    LlmMessage(
                        role=MessageRole.user,
                        content=(
                            "Your answer cited an unknown evidence ref or had no citation. "
                            "Rewrite it using ONLY these refs, and cite one in every sentence: "
                            + ", ".join(f"[{r}]" for r in sorted(valid_refs))
                        ),
                    )
                )

        await self._emit("ungrounded_output")
        return self._template(req, bundle, "ungrounded_output", evidence_flagged=flagged)

    # ---- helpers -------------------------------------------------
    @staticmethod
    def _confidence(live: bool, flagged: bool, n_cites: int) -> str:
        if not live:
            return "low"
        if flagged or n_cites < 2:
            return "medium"
        return "high"

    def _template(
        self, req: ExplainRequest, bundle: EvidenceBundle, reason: str, *, evidence_flagged: bool
    ) -> Explanation:
        lines = [
            "LLM analysis is unavailable — this is a factual summary of the gathered evidence.",
        ]
        for item in bundle.items:
            snippet = " ".join(item.content.split())[:240]
            lines.append(f"- {item.kind} [{item.ref}] (source {item.provenance}): {snippet}")
        return Explanation(
            subject_type=req.subject_type,
            subject_id=req.subject_id,
            summary="\n".join(lines),
            cited_refs=[i.ref for i in bundle.items],
            confidence="low",
            recommendations=_RECOMMENDATIONS.get(req.subject_type, []),
            model=AnalystModelInfo(),
            generated_at=utcnow(),
            degraded=True,
            degraded_reason=reason,
            evidence_flagged=evidence_flagged,
        )

    async def _emit(self, event: str) -> None:
        if self._audit is None:
            return
        result = self._audit(event)
        if asyncio.iscoroutine(result):
            await result
