"""SentinelMesh canonical contracts.

Single source of truth for the event envelope, the API error contract, and the
Phase-1 entity / API schemas. TypeScript types for the frontend are generated
from the JSON Schema this package emits (`scripts/gen_contracts.py`).

Import surface is intentionally flat for consumers:

    from sm_contracts import EventEnvelope, ErrorResponse, User
"""

from __future__ import annotations

from .api import (
    AgentFinding,
    AgentRunRequest,
    AgentRunResult,
    AnalystModelInfo,
    AttackProgressionRequest,
    BlastRadiusRequest,
    BlastRadiusResult,
    CreateUserRequest,
    CursorPage,
    Decoy,
    DecoyInteraction,
    DecoyInteractionIn,
    DecoyKind,
    DepStatus,
    EntitySelector,
    EvidenceRef,
    ExplainRequest,
    Explanation,
    GrantRoleRequest,
    GraphEdge,
    GraphNeighborhood,
    GraphNode,
    GraphPath,
    HealthResponse,
    HuntExplainRequest,
    HuntResult,
    LateralMovementRequest,
    LoginRequest,
    LoginResponse,
    LogoutResponse,
    MeResponse,
    MetaResponse,
    MitreHeatmap,
    MitreHeatmapCell,
    NetworkBoundary,
    NextActionRequest,
    NlHuntRequest,
    PlanResponse,
    Prediction,
    PredictionKind,
    ProposedActionOut,
    QueryLimits,
    QueryPlan,
    ReadyResponse,
    RegisterDecoyRequest,
    RiskSubject,
    RoleSummary,
    RunScenarioRequest,
    ScenarioKind,
    ScenarioRunResult,
    SimEventOut,
    SocHuntRequest,
    SocHuntResponse,
    SocSummary,
    ThreatTrajectoryRequest,
    TimelineEntry,
    TimelineResponse,
    TwinAssetOut,
    TwinRelationOut,
    TwinSnapshot,
    TwinWeaknessOut,
    UserResponse,
)
from .chains import (
    CHAIN_PAYLOADS,
    CONFIDENCE_CEILING,
    N_KILL_CHAIN_STAGES,
    STAGE_ORDER,
    TACTIC_STAGE,
    TECHNIQUE_STAGE,
    AttackChainModel,
    AttackChainPayload,
    AttackStage,
    ChainStageModel,
    ChainStatus,
    chain_dedup_key,
    chain_id_for,
    chain_window_start,
    stage_for_tactic,
    stage_for_technique,
    stages_for_techniques,
)
from .common import SmBaseModel, TenantScoped, TimestampedModel, to_utc
from .detection import (
    DETECTION_PAYLOADS,
    DetectionPayload,
    EvidenceItem,
    EvidenceKind,
    detection_dedup_key,
    detection_id_for,
)
from .entities import (
    Anomaly,
    AuditRecord,
    Detection,
    Permission,
    Role,
    RolePermission,
    SecurityAlert,
    Sensor,
    Tenant,
    ThreatScore,
    User,
    UserRoleGrant,
)
from .enums import (
    ActorType,
    AlertStatus,
    AnomalyMethod,
    AuditResult,
    DetectionStatus,
    DetectorKind,
    PermissionCode,
    ScoringStatus,
    SensorStatus,
    SensorType,
    Severity,
    SystemRole,
    TenantStatus,
    ThreatSubjectType,
    UserStatus,
)
from .errors import (
    HTTP_STATUS_BY_CODE,
    ErrorBody,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
)
from .events import (
    EVENT_PAYLOAD_REGISTRY,
    EventEnvelope,
    EventSource,
    EventType,
    SourceType,
    UserEventAction,
    UserEventPayload,
    make_partition_key,
)
from .graph import (
    GRAPH_NODE_KEY,
    GRAPH_NODE_LABELS,
    GRAPH_PAYLOADS,
    GRAPH_REL_TYPES,
    GraphCommandPayload,
    GraphEndpoint,
    GraphEventPayload,
    GraphMutationOutcome,
    GraphOp,
    graph_command_id,
    graph_node_uid,
    normalize_label,
)
from .memory import (
    MEMORY_PAYLOADS,
    AdversaryFingerprint,
    Campaign,
    CampaignStatus,
    CampaignUpdatePayload,
    MemoryPatternKind,
    SimilarityMatch,
    ThreatMemory,
)
from .mitre import (
    AttackMatrixVersion,
    AttackTactic,
    AttackTechnique,
    MappingConfidence,
    MappingSource,
    MappingSubjectType,
    TechniqueMapping,
    TechniqueMatch,
    is_technique_id,
    parent_technique_id,
)
from .telemetry import (
    TELEMETRY_PAYLOADS,
    AuthEventPayload,
    AuthOutcome,
    CanonicalEventPayload,
    CanonicalKind,
    Direction,
    DnsQueryPayload,
    EntityKind,
    EntityRef,
    FileAccessPayload,
    FileAction,
    NetworkFlowPayload,
    ProcessExecPayload,
)
from .threatintel import (
    TI_PAYLOADS,
    EnrichmentMatch,
    IndicatorFreshness,
    IndicatorType,
    Provenance,
    ThreatActor,
    ThreatIndicator,
    TiCampaign,
    TiConfidence,
    TiSource,
    TiSourceKind,
    TiUpdateAction,
    TiUpdatePayload,
    freshness_for,
    indicator_dedup_key,
    normalize_indicator_value,
)
from .topics import (
    EVENT_TYPE_TOPIC,
    EVENT_TYPE_VERSION,
    TOPICS,
    TopicSpec,
    dlq_topic,
    replay_group,
    topic_for_event_type,
)
from .version import CONTRACTS_VERSION, ENVELOPE_SCHEMA_VERSION

__all__ = [  # noqa: RUF022  (grouped by domain for readability, not alphabetically)
    "CONTRACTS_VERSION",
    "ENVELOPE_SCHEMA_VERSION",
    # base
    "SmBaseModel",
    "TimestampedModel",
    "TenantScoped",
    "to_utc",
    # errors
    "ErrorCode",
    "ErrorDetail",
    "ErrorBody",
    "ErrorResponse",
    "HTTP_STATUS_BY_CODE",
    # events
    "EventEnvelope",
    "make_partition_key",
    "EventType",
    "SourceType",
    "EventSource",
    "UserEventAction",
    "UserEventPayload",
    "EVENT_PAYLOAD_REGISTRY",
    # telemetry payloads (Phase 2)
    "NetworkFlowPayload",
    "AuthEventPayload",
    "DnsQueryPayload",
    "ProcessExecPayload",
    "FileAccessPayload",
    "CanonicalEventPayload",
    "EntityRef",
    "EntityKind",
    "CanonicalKind",
    "Direction",
    "AuthOutcome",
    "FileAction",
    "TELEMETRY_PAYLOADS",
    # topics (Phase 3)
    "TOPICS",
    "TopicSpec",
    "EVENT_TYPE_TOPIC",
    "EVENT_TYPE_VERSION",
    "topic_for_event_type",
    "dlq_topic",
    "replay_group",
    # graph commands (Phase 3) + graph model allowlist + graph events (Phase 4)
    "GraphCommandPayload",
    "GraphEndpoint",
    "GraphEventPayload",
    "GraphMutationOutcome",
    "GraphOp",
    "GRAPH_PAYLOADS",
    "graph_command_id",
    "graph_node_uid",
    "GRAPH_NODE_LABELS",
    "GRAPH_NODE_KEY",
    "GRAPH_REL_TYPES",
    "normalize_label",
    # detection + anomaly (Phase 5)
    "DetectionPayload",
    "DETECTION_PAYLOADS",
    "EvidenceItem",
    "EvidenceKind",
    "detection_dedup_key",
    "detection_id_for",
    "Severity",
    "DetectorKind",
    "AnomalyMethod",
    "ScoringStatus",
    "DetectionStatus",
    "AlertStatus",
    "ThreatSubjectType",
    # MITRE ATT&CK (Phase 6)
    "AttackTactic",
    "AttackTechnique",
    "AttackMatrixVersion",
    "TechniqueMapping",
    "TechniqueMatch",
    "MappingConfidence",
    "MappingSource",
    "MappingSubjectType",
    "is_technique_id",
    "parent_technique_id",
    # attack chains + correlation (Phase 7)
    "AttackChainModel",
    "AttackChainPayload",
    "AttackStage",
    "ChainStageModel",
    "ChainStatus",
    "CHAIN_PAYLOADS",
    "CONFIDENCE_CEILING",
    "N_KILL_CHAIN_STAGES",
    "STAGE_ORDER",
    "TACTIC_STAGE",
    "TECHNIQUE_STAGE",
    "chain_dedup_key",
    "chain_id_for",
    "chain_window_start",
    "stage_for_tactic",
    "stage_for_technique",
    "stages_for_techniques",
    # threat intelligence (Phase 6)
    "ThreatIndicator",
    "ThreatActor",
    "TiCampaign",
    "TiSource",
    "EnrichmentMatch",
    "Provenance",
    "TiUpdatePayload",
    "TI_PAYLOADS",
    "IndicatorType",
    "IndicatorFreshness",
    "TiConfidence",
    "TiSourceKind",
    "TiUpdateAction",
    "normalize_indicator_value",
    "indicator_dedup_key",
    "freshness_for",
    # enums
    "TenantStatus",
    "UserStatus",
    "SystemRole",
    "PermissionCode",
    "ActorType",
    "AuditResult",
    "SensorType",
    "SensorStatus",
    # entities
    "Tenant",
    "User",
    "Role",
    "Permission",
    "RolePermission",
    "UserRoleGrant",
    "Sensor",
    "AuditRecord",
    "Detection",
    "Anomaly",
    "ThreatScore",
    "SecurityAlert",
    # api
    "LoginRequest",
    "LoginResponse",
    "LogoutResponse",
    "MeResponse",
    "CreateUserRequest",
    "GrantRoleRequest",
    "RoleSummary",
    "UserResponse",
    "CursorPage",
    "HealthResponse",
    "ReadyResponse",
    "MetaResponse",
    "DepStatus",
    # SOC read API (Phase 9)
    "SocSummary",
    "RiskSubject",
    "MitreHeatmap",
    "MitreHeatmapCell",
    "TimelineEntry",
    "TimelineResponse",
    "GraphNode",
    "GraphEdge",
    "GraphNeighborhood",
    "GraphPath",
    # AI analyst (Phase 10)
    "EvidenceRef",
    "ExplainRequest",
    "Explanation",
    "AnalystModelInfo",
    # multi-agent defense (Phase 10)
    "AgentRunRequest",
    "AgentRunResult",
    "AgentFinding",
    "ProposedActionOut",
    # threat hunting (Phase 11)
    "QueryPlan",
    "EntitySelector",
    "QueryLimits",
    "NlHuntRequest",
    "PlanResponse",
    "HuntResult",
    "HuntExplainRequest",
    "SocHuntRequest",
    "SocHuntResponse",
    "Decoy",
    "DecoyInteraction",
    "DecoyInteractionIn",
    "DecoyKind",
    "NetworkBoundary",
    "RegisterDecoyRequest",
    "RunScenarioRequest",
    "ScenarioKind",
    "ScenarioRunResult",
    "SimEventOut",
    "TwinAssetOut",
    "TwinRelationOut",
    "TwinSnapshot",
    "TwinWeaknessOut",
    "BlastRadiusRequest",
    "BlastRadiusResult",
    # threat memory (Phase 13)
    "ThreatMemory",
    "Campaign",
    "CampaignStatus",
    "AdversaryFingerprint",
    "SimilarityMatch",
    "MemoryPatternKind",
    "CampaignUpdatePayload",
    "MEMORY_PAYLOADS",
    # predictive intelligence (Phase 13)
    "Prediction",
    "PredictionKind",
    "AttackProgressionRequest",
    "NextActionRequest",
    "LateralMovementRequest",
    "ThreatTrajectoryRequest",
]
