"""Phase 1 API request/response contracts (docs/CONTRACTS.md §1.2)."""

from __future__ import annotations

from .agent import (
    AgentFinding,
    AgentRunRequest,
    AgentRunResult,
    ProposedActionOut,
)
from .analyst import (
    AnalystModelInfo,
    EvidenceRef,
    ExplainRequest,
    Explanation,
)
from .auth import LoginRequest, LoginResponse, LogoutResponse, MeResponse
from .graph import GraphEdge, GraphNeighborhood, GraphNode, GraphPath
from .health import DepStatus, HealthResponse, MetaResponse, ReadyResponse
from .hunt import (
    EntitySelector,
    HuntExplainRequest,
    HuntResult,
    NlHuntRequest,
    PlanResponse,
    QueryLimits,
    QueryPlan,
    SocHuntRequest,
    SocHuntResponse,
)
from .pagination import CursorPage
from .prediction import (
    AttackProgressionRequest,
    LateralMovementRequest,
    NextActionRequest,
    Prediction,
    PredictionKind,
    ThreatTrajectoryRequest,
)
from .simulation import (
    BlastRadiusRequest,
    BlastRadiusResult,
    Decoy,
    DecoyInteraction,
    DecoyInteractionIn,
    DecoyKind,
    NetworkBoundary,
    RegisterDecoyRequest,
    RunScenarioRequest,
    ScenarioKind,
    ScenarioRunResult,
    SimEventOut,
    TwinAssetOut,
    TwinRelationOut,
    TwinSnapshot,
    TwinWeaknessOut,
)
from .soc import (
    MitreHeatmap,
    MitreHeatmapCell,
    RiskSubject,
    SocSummary,
    TimelineEntry,
    TimelineResponse,
)
from .users import CreateUserRequest, GrantRoleRequest, RoleSummary, UserResponse

__all__ = [
    "AgentFinding",
    "AgentRunRequest",
    "AgentRunResult",
    "AnalystModelInfo",
    "AttackProgressionRequest",
    "BlastRadiusRequest",
    "BlastRadiusResult",
    "CreateUserRequest",
    "CursorPage",
    "Decoy",
    "DecoyInteraction",
    "DecoyInteractionIn",
    "DecoyKind",
    "DepStatus",
    "EntitySelector",
    "EvidenceRef",
    "ExplainRequest",
    "Explanation",
    "GrantRoleRequest",
    "GraphEdge",
    "GraphNeighborhood",
    "GraphNode",
    "GraphPath",
    "HealthResponse",
    "HuntExplainRequest",
    "HuntResult",
    "LateralMovementRequest",
    "LoginRequest",
    "LoginResponse",
    "LogoutResponse",
    "MeResponse",
    "MetaResponse",
    "MitreHeatmap",
    "MitreHeatmapCell",
    "NetworkBoundary",
    "NextActionRequest",
    "NlHuntRequest",
    "PlanResponse",
    "Prediction",
    "PredictionKind",
    "ProposedActionOut",
    "QueryLimits",
    "QueryPlan",
    "ReadyResponse",
    "RegisterDecoyRequest",
    "RiskSubject",
    "RoleSummary",
    "RunScenarioRequest",
    "ScenarioKind",
    "ScenarioRunResult",
    "SimEventOut",
    "SocHuntRequest",
    "SocHuntResponse",
    "SocSummary",
    "ThreatTrajectoryRequest",
    "TimelineEntry",
    "TimelineResponse",
    "TwinAssetOut",
    "TwinRelationOut",
    "TwinSnapshot",
    "TwinWeaknessOut",
    "UserResponse",
]
